import type { TaskTimerElements } from "./elements";
import type { TaskTimerRuntime } from "./runtime";
import type { AppPage, HistoryViewState, MainMode } from "./types";
import type { DeletedTaskMeta, HistoryByTaskId, Task } from "../lib/types";
import type { FriendProfile, FriendRequest, Friendship, SharedTaskSummary } from "../lib/friendsStore";

export type TaskTimerAppPageSyncUrlMode = "replace" | "push" | false;

export type TaskTimerCachedModeSettings =
  | Partial<
      Record<
        MainMode,
        {
          label?: unknown;
          enabled?: unknown;
        }
      >
    >
  | Record<string, unknown>
  | null;

export type TaskTimerCachedPreferences = {
  theme?: unknown;
  menuButtonStyle?: unknown;
  defaultTaskTimerFormat?: unknown;
  taskView?: unknown;
  autoFocusOnTaskLaunchEnabled?: unknown;
  dynamicColorsEnabled?: unknown;
  checkpointAlertSoundEnabled?: unknown;
  checkpointAlertToastEnabled?: unknown;
  modeSettings?: TaskTimerCachedModeSettings;
};

export type TaskTimerConfirmOptions = {
  okLabel?: string;
  cancelLabel?: string;
  checkboxLabel?: string;
  checkboxChecked?: boolean;
  textHtml?: string;
  onOk?: (() => void) | null;
  onCancel?: (() => void) | null;
};

export type TaskTimerAppShellContext = {
  els: TaskTimerElements;
  runtime: TaskTimerRuntime;
  on: TaskTimerRuntime["on"];
  initialAppPage: AppPage;
  navStackKey: string;
  navStackMax: number;
  nativeBackDebounceMs: number;
  getCurrentAppPage: () => AppPage;
  setCurrentAppPage: (page: AppPage) => void;
  getSuppressNavStackPush: () => boolean;
  setSuppressNavStackPush: (value: boolean) => void;
  getNavStackMemory: () => string[];
  setNavStackMemory: (stack: string[]) => void;
  getLastNativeBackHandledAtMs: () => number;
  setLastNativeBackHandledAtMs: (ms: number) => void;
  resetAllOpenHistoryChartSelections: () => void;
  clearTaskFlipStates: () => void;
  renderFriendsFooterAlertBadge: () => void;
  closeTaskExportModal: () => void;
  closeShareTaskModal: () => void;
  closeFriendProfileModal: () => void;
  closeFriendRequestModal: () => void;
  render: () => void;
  renderHistory: (taskId: string) => void;
  renderDashboardWidgets: (opts?: { includeAvgSession?: boolean }) => void;
  renderGroupsPage: () => void;
  refreshGroupsData: (opts?: { preserveStatus?: boolean }) => Promise<void>;
  getOpenHistoryTaskIds: () => Iterable<string>;
  closeTopOverlayIfOpen: () => boolean;
  closeMobileDetailPanelIfOpen: () => boolean;
  showExitAppConfirm: () => void;
};

export type TaskTimerGroupsContext = {
  els: TaskTimerElements;
  on: TaskTimerRuntime["on"];
  getTasks: () => Task[];
  getHistoryByTaskId: () => HistoryByTaskId;
  getCurrentUid: () => string | null;
  getCurrentAppPage: () => AppPage;
  getCurrentMode: () => MainMode;
  applyMainMode: (mode: MainMode) => void;
  applyAppPage: (page: AppPage, opts?: { pushNavStack?: boolean; syncUrl?: TaskTimerAppPageSyncUrlMode }) => void;
  render: () => void;
  closeConfirm: () => void;
  confirm: (title: string, text: string, opts: TaskTimerConfirmOptions) => void;
  escapeHtmlUI: (value: unknown) => string;
  taskModeOf: (task: Task | null | undefined) => MainMode;
  normalizeHistoryTimestampMs: (value: unknown) => number;
  showWorkingIndicator: (message: string) => number;
  hideWorkingIndicator: (key?: number) => void;
  getMergedFriendProfile: (friendUid: string, baseProfile?: FriendProfile | null) => FriendProfile;
  getFriendAvatarSrcById: (avatarIdRaw: string) => string;
  buildFriendInitialAvatarDataUrl: (labelRaw: string) => string;
  getFriendAvatarSrc: (profile?: FriendProfile | null) => string;
  jumpToTaskById: (taskId: string) => void;
  getGroupsIncomingRequests: () => FriendRequest[];
  setGroupsIncomingRequests: (value: FriendRequest[]) => void;
  getGroupsOutgoingRequests: () => FriendRequest[];
  setGroupsOutgoingRequests: (value: FriendRequest[]) => void;
  getGroupsFriendships: () => Friendship[];
  setGroupsFriendships: (value: Friendship[]) => void;
  getGroupsSharedSummaries: () => SharedTaskSummary[];
  setGroupsSharedSummaries: (value: SharedTaskSummary[]) => void;
  getOwnSharedSummaries: () => SharedTaskSummary[];
  setOwnSharedSummaries: (value: SharedTaskSummary[]) => void;
  getGroupsLoading: () => boolean;
  setGroupsLoading: (value: boolean) => void;
  getGroupsLoadingDepth: () => number;
  setGroupsLoadingDepth: (value: number) => void;
  getGroupsRefreshSeq: () => number;
  setGroupsRefreshSeq: (value: number) => void;
  getActiveFriendProfileUid: () => string | null;
  setActiveFriendProfileUid: (value: string | null) => void;
  getActiveFriendProfileName: () => string;
  setActiveFriendProfileName: (value: string) => void;
  getFriendProfileCacheByUid: () => Record<string, FriendProfile>;
  setFriendProfileCacheByUid: (value: Record<string, FriendProfile>) => void;
  getShareTaskIndex: () => number | null;
  setShareTaskIndex: (value: number | null) => void;
  getShareTaskMode: () => "share" | "unshare";
  setShareTaskMode: (value: "share" | "unshare") => void;
  getShareTaskTaskId: () => string | null;
  setShareTaskTaskId: (value: string | null) => void;
  getOpenFriendSharedTaskUids: () => Set<string>;
};

export type TaskTimerPreferencesContext = {
  els: TaskTimerElements;
  on: TaskTimerRuntime["on"];
  storageKeys: {
    THEME_KEY: string;
    TASK_VIEW_KEY: string;
    AUTO_FOCUS_ON_TASK_LAUNCH_KEY: string;
    MENU_BUTTON_STYLE_KEY: string;
    MODE_SETTINGS_KEY: string;
    DEFAULT_TASK_TIMER_FORMAT_KEY: string;
  };
  defaultModeLabels: Record<MainMode, string>;
  defaultModeEnabled: Record<MainMode, boolean>;
  defaultModeColors: Record<MainMode, string>;
  getThemeMode: () => "purple" | "cyan";
  setThemeModeState: (value: "purple" | "cyan") => void;
  getTaskView: () => "list" | "tile";
  setTaskViewState: (value: "list" | "tile") => void;
  getMenuButtonStyle: () => "parallelogram" | "square";
  setMenuButtonStyleState: (value: "parallelogram" | "square") => void;
  getDefaultTaskTimerFormat: () => "day" | "hour" | "minute";
  setDefaultTaskTimerFormatState: (value: "day" | "hour" | "minute") => void;
  getAutoFocusOnTaskLaunchEnabled: () => boolean;
  setAutoFocusOnTaskLaunchEnabledState: (value: boolean) => void;
  getDynamicColorsEnabled: () => boolean;
  setDynamicColorsEnabledState: (value: boolean) => void;
  getCheckpointAlertSoundEnabled: () => boolean;
  setCheckpointAlertSoundEnabledState: (value: boolean) => void;
  getCheckpointAlertToastEnabled: () => boolean;
  setCheckpointAlertToastEnabledState: (value: boolean) => void;
  getModeLabels: () => Record<MainMode, string>;
  setModeLabelsState: (value: Record<MainMode, string>) => void;
  getModeEnabled: () => Record<MainMode, boolean>;
  setModeEnabledState: (value: Record<MainMode, boolean>) => void;
  getCurrentMode: () => MainMode;
  getEditMoveTargetMode: () => MainMode;
  setEditMoveTargetModeState: (value: MainMode) => void;
  persistPreferencesToCloud: () => void;
  loadCachedPreferences: () => TaskTimerCachedPreferences | null | undefined;
  loadCachedTaskUi: () => unknown;
  getCloudPreferencesCache: () => TaskTimerCachedPreferences | null | undefined;
  saveDashboardWidgetState: (partialWidgets: Record<string, unknown>) => void;
  getDashboardCardSizeMapForStorage: () => Record<string, unknown>;
  getDashboardAvgRange: () => string;
  getCurrentEditTask: () => Task | null;
  syncEditCheckpointAlertUi: (task: Task) => void;
  applyMainMode: (mode: MainMode) => void;
  clearTaskFlipStates: () => void;
  render: () => void;
  renderDashboardPanelMenu: () => void;
  renderDashboardWidgets: (opts?: { includeAvgSession?: boolean }) => void;
  ensureDashboardIncludedModesValid: () => void;
  closeOverlay: (overlay: HTMLElement | null) => void;
  closeConfirm: () => void;
  confirm: (title: string, text: string, opts: TaskTimerConfirmOptions) => void;
  deleteTasksInMode: (mode: MainMode) => void;
  escapeHtmlUI: (value: unknown) => string;
  stopCheckpointRepeatAlert: () => void;
  getCurrentAppPage: () => AppPage;
};

export type TaskTimerHistoryManagerSortKey = "ts" | "ms";
export type TaskTimerHistoryManagerSortDir = "asc" | "desc";

export type TaskTimerHistoryManagerContext = {
  els: TaskTimerElements;
  on: TaskTimerRuntime["on"];
  runtime: TaskTimerRuntime;
  getTasks: () => Task[];
  getHistoryByTaskId: () => HistoryByTaskId;
  setHistoryByTaskId: (value: HistoryByTaskId) => void;
  getDeletedTaskMeta: () => DeletedTaskMeta;
  setDeletedTaskMeta: (value: DeletedTaskMeta) => void;
  getHmExpandedTaskGroups: () => Set<string>;
  setHmExpandedTaskGroups: (value: Set<string>) => void;
  getHmExpandedDateGroups: () => Set<string>;
  setHmExpandedDateGroups: (value: Set<string>) => void;
  getHmSortKey: () => TaskTimerHistoryManagerSortKey;
  setHmSortKey: (value: TaskTimerHistoryManagerSortKey) => void;
  getHmSortDir: () => TaskTimerHistoryManagerSortDir;
  setHmSortDir: (value: TaskTimerHistoryManagerSortDir) => void;
  getHmBulkEditMode: () => boolean;
  setHmBulkEditMode: (value: boolean) => void;
  getHmBulkSelectedRows: () => Set<string>;
  setHmBulkSelectedRows: (value: Set<string>) => void;
  getHmRowsByTask: () => Record<string, string[]>;
  setHmRowsByTask: (value: Record<string, string[]>) => void;
  getHmRowsByTaskDate: () => Record<string, string[]>;
  setHmRowsByTaskDate: (value: Record<string, string[]>) => void;
  getHistoryManagerRefreshInFlight: () => Promise<void> | null;
  setHistoryManagerRefreshInFlight: (value: Promise<void> | null) => void;
  isArchitectUser: () => boolean;
  getHistoryEntryNote: (entry: unknown) => string;
  csvEscape: (value: unknown) => string;
  parseCsvRows: (input: string) => string[][];
  downloadCsvFile: (filename: string, text: string) => void;
  formatTwo: (value: number) => string;
  formatDateTime: (value: number) => string;
  sortMilestones: (milestones: Task["milestones"]) => Task["milestones"];
  sessionColorForTaskMs: (task: Task, elapsedMs: number) => string;
  saveHistory: (history: HistoryByTaskId) => void;
  saveHistoryAndWait: (history: HistoryByTaskId) => Promise<void>;
  loadHistory: () => HistoryByTaskId;
  refreshHistoryFromCloud: () => Promise<HistoryByTaskId>;
  saveDeletedMeta: (meta: DeletedTaskMeta) => void;
  loadDeletedMeta: () => DeletedTaskMeta;
  load: () => void;
  render: () => void;
  navigateToAppRoute: (path: string) => void;
  confirm: (title: string, text: string, opts: TaskTimerConfirmOptions) => void;
  closeConfirm: () => void;
  escapeHtmlUI: (value: unknown) => string;
  syncSharedTaskSummariesForTasks: (taskIds: string[]) => Promise<void>;
  syncSharedTaskSummariesForTask: (taskId: string) => Promise<void>;
};

export type TaskTimerHistoryInlineContext = {
  els: TaskTimerElements;
  on: TaskTimerRuntime["on"];
  getTasks: () => Task[];
  getHistoryByTaskId: () => HistoryByTaskId;
  setHistoryByTaskId: (value: HistoryByTaskId) => void;
  getHistoryRangeDaysByTaskId: () => Record<string, 7 | 14>;
  getHistoryRangeModeByTaskId: () => Record<string, "entries" | "day">;
  getHistoryViewByTaskId: () => Record<string, HistoryViewState>;
  getOpenHistoryTaskIds: () => Set<string>;
  getCurrentAppPage: () => AppPage;
  getPinnedHistoryTaskIds: () => Set<string>;
  setPinnedHistoryTaskIds: (value: Set<string>) => void;
  savePinnedHistoryTaskIds: () => void;
  getHistoryEntryNoteAnchorTaskId: () => string;
  setHistoryEntryNoteAnchorTaskId: (value: string) => void;
  persistTaskUiToCloud: () => void;
  saveHistory: (history: HistoryByTaskId) => void;
  confirm: (title: string, text: string, opts: TaskTimerConfirmOptions) => void;
  closeConfirm: () => void;
  navigateToAppRoute: (path: string) => void;
  openOverlay: (overlay: HTMLElement | null) => void;
  closeOverlay: (overlay: HTMLElement | null) => void;
  render: () => void;
  renderDashboardWidgets: (opts?: { includeAvgSession?: boolean }) => void;
  nowMs: () => number;
  normalizeHistoryTimestampMs: (value: unknown) => number;
  formatTime: (value: number) => string;
  formatTwo: (value: number) => string;
  formatDateTime: (value: number) => string;
  escapeHtmlUI: (value: unknown) => string;
  sortMilestones: (milestones: Task["milestones"]) => Task["milestones"];
  sessionColorForTaskMs: (task: Task, elapsedMs: number) => string;
  getModeColor: (mode: MainMode) => string;
  taskModeOf: (task: Task | null | undefined) => MainMode;
  milestoneUnitSec: (task: Task | undefined | null) => number;
  milestoneUnitSuffix: (task: Task | undefined | null) => string;
  getDynamicColorsEnabled: () => boolean;
};
