export function collectTaskTimerElements(documentRef: Document) {
const els = {
  taskList: documentRef.getElementById("taskList"),
  openAddTaskBtn: documentRef.getElementById("openAddTaskBtn"),
  addTaskOverlay: documentRef.getElementById("addTaskOverlay"),
  addTaskForm: documentRef.getElementById("addTaskForm"),
  addTaskName: documentRef.getElementById("addTaskName") as HTMLInputElement | null,
  addTaskNameCombo: documentRef.getElementById("addTaskNameCombo"),
  addTaskNameToggle: documentRef.getElementById("addTaskNameToggle"),
  addTaskNameMenu: documentRef.getElementById("addTaskNameMenu"),
  addTaskNameCustomTitle: documentRef.getElementById("addTaskNameCustomTitle"),
  addTaskNameCustomList: documentRef.getElementById("addTaskNameCustomList"),
  addTaskNameDivider: documentRef.getElementById("addTaskNameDivider"),
  addTaskNamePresetTitle: documentRef.getElementById("addTaskNamePresetTitle"),
  addTaskNamePresetList: documentRef.getElementById("addTaskNamePresetList"),
  addTaskWizardProgress: documentRef.getElementById("addTaskWizardProgress"),
  addTaskStep1: documentRef.getElementById("addTaskStep1"),
  addTaskStep2: documentRef.getElementById("addTaskStep2"),
  addTaskStep3: documentRef.getElementById("addTaskStep3"),
  addTaskCheckpointInfoBtn: documentRef.getElementById("addTaskCheckpointInfoBtn"),
  addTaskCheckpointInfoDialog: documentRef.getElementById("addTaskCheckpointInfoDialog"),
  addTaskDurationRow: documentRef.getElementById("addTaskDurationRow"),
  addTaskDurationValueInput: documentRef.getElementById("addTaskDurationValueInput") as HTMLInputElement | null,
  addTaskDurationUnitMinute: documentRef.getElementById("addTaskDurationUnitMinute") as HTMLButtonElement | null,
  addTaskDurationUnitHour: documentRef.getElementById("addTaskDurationUnitHour") as HTMLButtonElement | null,
  addTaskDurationPeriodDay: documentRef.getElementById("addTaskDurationPeriodDay") as HTMLButtonElement | null,
  addTaskDurationPeriodWeek: documentRef.getElementById("addTaskDurationPeriodWeek") as HTMLButtonElement | null,
  addTaskDurationReadout: documentRef.getElementById("addTaskDurationReadout"),
  addTaskNoGoalCheckbox: documentRef.getElementById("addTaskNoGoalCheckbox") as HTMLInputElement | null,
  addTaskStep1NextBtn: documentRef.getElementById("addTaskStep1NextBtn"),
  addTaskStep2BackBtn: documentRef.getElementById("addTaskStep2BackBtn"),
  addTaskStep2NextBtn: documentRef.getElementById("addTaskStep2NextBtn"),
  addTaskStep3BackBtn: documentRef.getElementById("addTaskStep3BackBtn"),
  addTaskConfirmBtn: documentRef.getElementById("addTaskConfirmBtn"),
  addTaskError: documentRef.getElementById("addTaskError"),
  addTaskMsToggle: documentRef.getElementById("addTaskMsToggle"),
  addTaskMsUnitRow: documentRef.getElementById("addTaskMsUnitRow"),
  addTaskMsUnitDay: documentRef.getElementById("addTaskMsUnitDay"),
  addTaskMsUnitHour: documentRef.getElementById("addTaskMsUnitHour"),
  addTaskMsUnitMinute: documentRef.getElementById("addTaskMsUnitMinute"),
  addTaskAddMsBtn: documentRef.getElementById("addTaskAddMsBtn") as HTMLButtonElement | null,
  addTaskMsArea: documentRef.getElementById("addTaskMsArea"),
  addTaskMsList: documentRef.getElementById("addTaskMsList"),
  addTaskCheckpointAlertsGroup: documentRef.getElementById("addTaskCheckpointAlertsGroup"),
  addTaskCheckpointSoundToggleRow: documentRef.getElementById("addTaskCheckpointSoundToggleRow"),
  addTaskCheckpointSoundToggle: documentRef.getElementById("addTaskCheckpointSoundToggle"),
  addTaskCheckpointSoundModeField: documentRef.getElementById("addTaskCheckpointSoundModeField"),
  addTaskCheckpointSoundModeSelect: documentRef.getElementById("addTaskCheckpointSoundModeSelect") as HTMLSelectElement | null,
  addTaskCheckpointToastToggleRow: documentRef.getElementById("addTaskCheckpointToastToggleRow"),
  addTaskCheckpointToastToggle: documentRef.getElementById("addTaskCheckpointToastToggle"),
  addTaskCheckpointToastModeField: documentRef.getElementById("addTaskCheckpointToastModeField"),
  addTaskCheckpointToastModeSelect: documentRef.getElementById("addTaskCheckpointToastModeSelect") as HTMLSelectElement | null,
  addTaskCheckpointAlertsNote: documentRef.getElementById("addTaskCheckpointAlertsNote"),
  addTaskTimerSettingsGroup: documentRef.getElementById("addTaskTimerSettingsGroup"),
  addTaskPresetIntervalsToggleRow: documentRef.getElementById("addTaskPresetIntervalsToggleRow"),
  addTaskPresetIntervalsToggle: documentRef.getElementById("addTaskPresetIntervalsToggle"),
  addTaskPresetIntervalsInfoBtn: documentRef.getElementById("addTaskPresetIntervalsInfoBtn"),
  addTaskPresetIntervalsInfoDialog: documentRef.getElementById("addTaskPresetIntervalsInfoDialog"),
  addTaskPresetIntervalField: documentRef.getElementById("addTaskPresetIntervalField"),
  addTaskPresetIntervalInput: documentRef.getElementById("addTaskPresetIntervalInput") as HTMLInputElement | null,
  addTaskPresetIntervalNote: documentRef.getElementById("addTaskPresetIntervalNote"),
  addTaskFinalCheckpointActionField: documentRef.getElementById("addTaskFinalCheckpointActionField"),
  addTaskFinalCheckpointActionSelect: documentRef.getElementById("addTaskFinalCheckpointActionSelect") as HTMLSelectElement | null,
  addTaskCancelBtn: documentRef.getElementById("addTaskCancelBtn"),
  resetAllBtn: documentRef.getElementById("resetAllBtn"),
  mode1Btn: documentRef.getElementById("mode1Btn") as HTMLButtonElement | null,
  mode2Btn: documentRef.getElementById("mode2Btn") as HTMLButtonElement | null,
  mode3Btn: documentRef.getElementById("mode3Btn") as HTMLButtonElement | null,
  modeSwitch: documentRef.getElementById("modeSwitch"),
  modeSwitchCurrentLabel: documentRef.getElementById("modeSwitchCurrentLabel"),
  mode1View: documentRef.getElementById("mode1View"),
  mode2View: documentRef.getElementById("mode2View"),
  mode3View: documentRef.getElementById("mode3View"),
  appPageTasks: documentRef.getElementById("appPageTasks"),
  appPageDashboard: documentRef.getElementById("appPageDashboard"),
  appPageTest1: documentRef.getElementById("appPageTest1"),
  appPageTest2: documentRef.getElementById("appPageTest2"),
  appRoot: documentRef.getElementById("app"),
  groupsFriendsSection: documentRef.getElementById("groupsFriendsSection"),
  openFriendRequestModalBtn: documentRef.getElementById("openFriendRequestModalBtn") as HTMLButtonElement | null,
  friendRequestModal: documentRef.getElementById("friendRequestModal"),
  friendRequestEmailInput: documentRef.getElementById("friendRequestEmailInput") as HTMLInputElement | null,
  friendRequestCancelBtn: documentRef.getElementById("friendRequestCancelBtn") as HTMLButtonElement | null,
  friendRequestSendBtn: documentRef.getElementById("friendRequestSendBtn") as HTMLButtonElement | null,
  friendRequestModalStatus: documentRef.getElementById("friendRequestModalStatus"),
  friendProfileModal: documentRef.getElementById("friendProfileModal"),
  friendProfileAvatar: documentRef.getElementById("friendProfileAvatar") as HTMLImageElement | null,
  friendProfileName: documentRef.getElementById("friendProfileName"),
  friendProfileRankImage: documentRef.getElementById("friendProfileRankImage") as HTMLImageElement | null,
  friendProfileRankPlaceholder: documentRef.getElementById("friendProfileRankPlaceholder"),
  friendProfileRank: documentRef.getElementById("friendProfileRank"),
  friendProfileMemberSince: documentRef.getElementById("friendProfileMemberSince"),
  friendProfileDeleteBtn: documentRef.getElementById("friendProfileDeleteBtn") as HTMLButtonElement | null,
  friendProfileCloseBtn: documentRef.getElementById("friendProfileCloseBtn") as HTMLButtonElement | null,
  shareTaskModal: documentRef.getElementById("shareTaskModal"),
  shareTaskTitle: documentRef.getElementById("shareTaskTitle"),
  shareTaskScopeSelect: documentRef.getElementById("shareTaskScopeSelect") as HTMLSelectElement | null,
  shareTaskFriendsField: documentRef.getElementById("shareTaskFriendsField"),
  shareTaskFriendsList: documentRef.getElementById("shareTaskFriendsList"),
  shareTaskStatus: documentRef.getElementById("shareTaskStatus"),
  shareTaskCancelBtn: documentRef.getElementById("shareTaskCancelBtn") as HTMLButtonElement | null,
  shareTaskConfirmBtn: documentRef.getElementById("shareTaskConfirmBtn") as HTMLButtonElement | null,
  exportTaskOverlay: documentRef.getElementById("exportTaskOverlay"),
  exportTaskTitle: documentRef.getElementById("exportTaskTitle"),
  exportTaskIncludeHistoryRow: documentRef.getElementById("exportTaskIncludeHistoryRow"),
  exportTaskIncludeHistory: documentRef.getElementById("exportTaskIncludeHistory") as HTMLInputElement | null,
  exportTaskIncludeHistoryLabel: documentRef.getElementById("exportTaskIncludeHistoryLabel"),
  exportTaskCancelBtn: documentRef.getElementById("exportTaskCancelBtn") as HTMLButtonElement | null,
  exportTaskConfirmBtn: documentRef.getElementById("exportTaskConfirmBtn") as HTMLButtonElement | null,
  groupsIncomingRequestsList: documentRef.getElementById("groupsIncomingRequestsList"),
  groupsIncomingRequestsDetails: documentRef.getElementById("groupsIncomingRequestsDetails") as HTMLDetailsElement | null,
  groupsIncomingRequestsTitle: documentRef.getElementById("groupsIncomingRequestsTitle"),
  groupsOutgoingRequestsDetails: documentRef.getElementById("groupsOutgoingRequestsDetails") as HTMLDetailsElement | null,
  groupsOutgoingRequestsTitle: documentRef.getElementById("groupsOutgoingRequestsTitle"),
  groupsOutgoingRequestsList: documentRef.getElementById("groupsOutgoingRequestsList"),
  groupsFriendsList: documentRef.getElementById("groupsFriendsList"),
  groupsSharedByYouList: documentRef.getElementById("groupsSharedByYouList"),
  groupsSharedByYouTitle: documentRef.getElementById("groupsSharedByYouTitle"),
  groupsFriendRequestStatus: documentRef.getElementById("groupsFriendRequestStatus"),
  historySaveWorkingIndicator: documentRef.getElementById("historySaveWorkingIndicator"),
  historySaveWorkingText: documentRef.getElementById("historySaveWorkingText"),
  footerTasksBtn: documentRef.getElementById("footerTasksBtn") as HTMLButtonElement | null,
  footerDashboardBtn: documentRef.getElementById("footerDashboardBtn") as HTMLButtonElement | null,
  footerTest1Btn: documentRef.getElementById("footerTest1Btn") as HTMLButtonElement | null,
  footerTest2Btn: documentRef.getElementById("footerTest2Btn") as HTMLButtonElement | null,
  footerTest2AlertBadge: documentRef.getElementById("footerTest2AlertBadge") as HTMLElement | null,
  footerSettingsBtn: documentRef.getElementById("footerSettingsBtn") as HTMLButtonElement | null,
  commandCenterTasksBtn: documentRef.getElementById("commandCenterTasksBtn") as HTMLButtonElement | null,
  commandCenterDashboardBtn: documentRef.getElementById("commandCenterDashboardBtn") as HTMLButtonElement | null,
  commandCenterGroupsBtn: documentRef.getElementById("commandCenterGroupsBtn") as HTMLButtonElement | null,
  commandCenterSettingsBtn: documentRef.getElementById("commandCenterSettingsBtn") as HTMLElement | null,
  rewardsInfoOpenBtn: documentRef.getElementById("rewardsInfoOpenBtn") as HTMLButtonElement | null,
  rewardsInfoOverlay: documentRef.getElementById("rewardsInfoOverlay") as HTMLElement | null,
  signedInHeaderBadge: documentRef.getElementById("signedInHeaderBadge") as HTMLElement | null,
  dashboardEditBtn: documentRef.getElementById("dashboardEditBtn") as HTMLButtonElement | null,
  dashboardEditCancelBtn: documentRef.getElementById("dashboardEditCancelBtn") as HTMLButtonElement | null,
  dashboardEditDoneBtn: documentRef.getElementById("dashboardEditDoneBtn") as HTMLButtonElement | null,
  dashboardPanelMenu: documentRef.getElementById("dashboardPanelMenu") as HTMLDetailsElement | null,
  dashboardPanelMenuBtn: documentRef.getElementById("dashboardPanelMenuBtn") as HTMLElement | null,
  dashboardPanelMenuList: documentRef.getElementById("dashboardPanelMenuList") as HTMLElement | null,
  dashboardGrid: documentRef.querySelector(".dashboardGrid") as HTMLElement | null,
  dashboardOverviewValue: documentRef.getElementById("dashboardOverviewValue"),
  dashboardOverviewSubtext: documentRef.getElementById("dashboardOverviewSubtext"),
  dashboardOverviewSessionsValue: documentRef.getElementById("dashboardOverviewSessionsValue"),
  dashboardOverviewBestDayValue: documentRef.getElementById("dashboardOverviewBestDayValue"),
  dashboardOverviewDeltaValue: documentRef.getElementById("dashboardOverviewDeltaValue"),
  dashboardOverviewChart: documentRef.getElementById("dashboardOverviewChart") as HTMLCanvasElement | null,
  dashboardOverviewChartEmpty: documentRef.getElementById("dashboardOverviewChartEmpty"),
  dashboardOverviewAxis: documentRef.getElementById("dashboardOverviewAxis"),
  dashboardAvgSessionChart: documentRef.getElementById("dashboardAvgSessionChart") as HTMLCanvasElement | null,
  dashboardAvgSessionEmpty: documentRef.getElementById("dashboardAvgSessionEmpty"),
  dashboardAvgSessionTitle: documentRef.getElementById("dashboardAvgSessionTitle"),
  dashboardFocusTrendCard: documentRef.getElementById("dashboardFocusTrendCard"),
  dashboardFocusTrendBars: documentRef.getElementById("dashboardFocusTrendBars"),
  dashboardFocusTrendAxis: documentRef.getElementById("dashboardFocusTrendAxis"),
  dashboardModeDonut: documentRef.getElementById("dashboardModeDonut"),
  dashboardModeDonutCenter: documentRef.getElementById("dashboardModeDonutCenter"),
  dashboardMode1Label: documentRef.getElementById("dashboardMode1Label"),
  dashboardMode2Label: documentRef.getElementById("dashboardMode2Label"),
  dashboardMode3Label: documentRef.getElementById("dashboardMode3Label"),
  dashboardMode1Value: documentRef.getElementById("dashboardMode1Value"),
  dashboardMode2Value: documentRef.getElementById("dashboardMode2Value"),
  dashboardMode3Value: documentRef.getElementById("dashboardMode3Value"),
  dashboardHeatMonthLabel: documentRef.getElementById("dashboardHeatMonthLabel"),
  dashboardHeatCalendarGrid: documentRef.getElementById("dashboardHeatCalendarGrid"),

  menuIcon: documentRef.getElementById("menuIcon"),
  menuOverlay: documentRef.getElementById("menuOverlay"),
  historyManagerScreen: documentRef.getElementById("historyManagerScreen"),
  historyManagerBtn: documentRef.getElementById("historyManagerBtn"),
  historyManagerExportBtn: documentRef.getElementById("historyManagerExportBtn") as HTMLButtonElement | null,
  historyManagerImportBtn: documentRef.getElementById("historyManagerImportBtn") as HTMLButtonElement | null,
  historyManagerGenerateBtn: documentRef.getElementById("historyManagerGenerateBtn") as HTMLButtonElement | null,
  historyManagerImportFile: documentRef.getElementById("historyManagerImportFile") as HTMLInputElement | null,
  historyManagerBulkBtn: documentRef.getElementById("historyManagerBulkBtn") as HTMLButtonElement | null,
  historyManagerBulkDeleteBtn: documentRef.getElementById("historyManagerBulkDeleteBtn") as HTMLButtonElement | null,
  historyManagerBackBtn: documentRef.getElementById("historyManagerBackBtn"),
  focusModeScreen: documentRef.getElementById("focusModeScreen"),
  focusModeBackBtn: documentRef.getElementById("focusModeBackBtn"),
  focusDial: documentRef.getElementById("focusDial"),
  focusCheckpointRing: documentRef.getElementById("focusCheckpointRing"),
  focusCheckpointToggle: documentRef.getElementById("focusCheckpointToggle"),
  focusCheckpointLog: documentRef.getElementById("focusCheckpointLog"),
  focusCheckpointLogEmpty: documentRef.getElementById("focusCheckpointLogEmpty"),
  focusCheckpointLogList: documentRef.getElementById("focusCheckpointLogList"),
  focusSessionNotesSection: documentRef.getElementById("focusSessionNotesSection") as HTMLDetailsElement | null,
  focusTaskName: documentRef.getElementById("focusTaskName"),
  focusTimerDays: documentRef.getElementById("focusTimerDays"),
  focusTimerClock: documentRef.getElementById("focusTimerClock"),
  focusDialHint: documentRef.getElementById("focusDialHint"),
  focusResetBtn: documentRef.getElementById("focusResetBtn") as HTMLButtonElement | null,
  focusInsightBest: documentRef.getElementById("focusInsightBest"),
  focusInsightWeekday: documentRef.getElementById("focusInsightWeekday"),
  focusInsightTodayDelta: documentRef.getElementById("focusInsightTodayDelta"),
  focusInsightWeekDelta: documentRef.getElementById("focusInsightWeekDelta"),
  focusSessionNotesInput: documentRef.getElementById("focusSessionNotesInput") as HTMLTextAreaElement | null,
  hmList: documentRef.getElementById("hmList"),
  closeMenuBtn: documentRef.getElementById("closeMenuBtn"),

  aboutOverlay: documentRef.getElementById("aboutOverlay"),
  howtoOverlay: documentRef.getElementById("howtoOverlay"),
  appearanceOverlay: documentRef.getElementById("appearanceOverlay"),
  taskSettingsOverlay: documentRef.getElementById("taskSettingsOverlay"),
  taskDefaultFormatDay: documentRef.getElementById("taskDefaultFormatDay"),
  taskDefaultFormatHour: documentRef.getElementById("taskDefaultFormatHour"),
  taskDefaultFormatMinute: documentRef.getElementById("taskDefaultFormatMinute"),
  taskAutoFocusOnLaunchToggleRow: documentRef.getElementById("taskAutoFocusOnLaunchToggleRow"),
  taskAutoFocusOnLaunchToggle: documentRef.getElementById("taskAutoFocusOnLaunchToggle"),
  taskDynamicColorsToggleRow: documentRef.getElementById("taskDynamicColorsToggleRow"),
  taskDynamicColorsToggle: documentRef.getElementById("taskDynamicColorsToggle"),
  taskViewSelect: documentRef.getElementById("taskViewSelect") as HTMLSelectElement | null,
  taskCheckpointSoundToggleRow: documentRef.getElementById("taskCheckpointSoundToggleRow"),
  taskCheckpointSoundToggle: documentRef.getElementById("taskCheckpointSoundToggle"),
  taskCheckpointToastToggleRow: documentRef.getElementById("taskCheckpointToastToggleRow"),
  taskCheckpointToastToggle: documentRef.getElementById("taskCheckpointToastToggle"),
  taskSettingsSaveBtn: documentRef.getElementById("taskSettingsSaveBtn"),
  preferencesLoadDefaultsBtn: documentRef.getElementById("preferencesLoadDefaultsBtn"),
  appearanceLoadDefaultsBtn: documentRef.getElementById("appearanceLoadDefaultsBtn"),
  categoryManagerOverlay: documentRef.getElementById("categoryManagerOverlay"),
  categoryMode1Input: documentRef.getElementById("categoryMode1Input") as HTMLInputElement | null,
  categoryMode2Input: documentRef.getElementById("categoryMode2Input") as HTMLInputElement | null,
  categoryMode3Input: documentRef.getElementById("categoryMode3Input") as HTMLInputElement | null,
  categoryMode2Toggle: documentRef.getElementById("categoryMode2Toggle"),
  categoryMode3Toggle: documentRef.getElementById("categoryMode3Toggle"),
  categoryMode2ToggleLabel: documentRef.getElementById("categoryMode2ToggleLabel"),
  categoryMode3ToggleLabel: documentRef.getElementById("categoryMode3ToggleLabel"),
  categoryMode2Row: documentRef.getElementById("categoryMode2Row"),
  categoryMode3Row: documentRef.getElementById("categoryMode3Row"),
  categoryMode2TrashBtn: documentRef.getElementById("categoryMode2TrashBtn"),
  categoryMode3TrashBtn: documentRef.getElementById("categoryMode3TrashBtn"),
  categorySaveBtn: documentRef.getElementById("categorySaveBtn"),
  categoryResetBtn: documentRef.getElementById("categoryResetBtn"),
  themeToggleRow: documentRef.getElementById("themeToggleRow"),
  themeSelect: documentRef.getElementById("themeSelect") as HTMLSelectElement | null,
  menuButtonStyleSelect: documentRef.getElementById("menuButtonStyleSelect") as HTMLSelectElement | null,
  contactOverlay: documentRef.getElementById("contactOverlay"),

  exportBtn: documentRef.getElementById("exportBtn"),
  importBtn: documentRef.getElementById("importBtn"),
  importFile: documentRef.getElementById("importFile") as HTMLInputElement | null,

  editOverlay: documentRef.getElementById("editOverlay"),
  editName: documentRef.getElementById("editName") as HTMLInputElement | null,
  editTaskDurationRow: documentRef.getElementById("editTaskDurationRow"),
  editTaskDurationValueInput: documentRef.getElementById("editTaskDurationValueInput") as HTMLInputElement | null,
  editTaskDurationUnitMinute: documentRef.getElementById("editTaskDurationUnitMinute") as HTMLButtonElement | null,
  editTaskDurationUnitHour: documentRef.getElementById("editTaskDurationUnitHour") as HTMLButtonElement | null,
  editTaskDurationPeriodDay: documentRef.getElementById("editTaskDurationPeriodDay") as HTMLButtonElement | null,
  editTaskDurationPeriodWeek: documentRef.getElementById("editTaskDurationPeriodWeek") as HTMLButtonElement | null,
  editTaskDurationReadout: documentRef.getElementById("editTaskDurationReadout"),
  editTimeGoalToggleRow: documentRef.getElementById("editTaskTimeGoalToggleRow"),
  editTimeGoalToggle: documentRef.getElementById("editTimeGoalToggle"),
  editNoGoalCheckbox: documentRef.getElementById("editNoGoalCheckbox") as HTMLInputElement | null,
  editAdvancedSection: documentRef.getElementById("editAdvancedSection") as HTMLDetailsElement | null,
  editMoveMenu: documentRef.getElementById("editMoveMenu") as HTMLDetailsElement | null,
  editMoveCurrentLabel: documentRef.getElementById("editMoveCurrentLabel"),
  editMoveMode1: documentRef.getElementById("editMoveMode1") as HTMLButtonElement | null,
  editMoveMode2: documentRef.getElementById("editMoveMode2") as HTMLButtonElement | null,
  editMoveMode3: documentRef.getElementById("editMoveMode3") as HTMLButtonElement | null,
  editOverrideElapsedToggle: documentRef.getElementById("editOverrideElapsedToggle"),
  editOverrideElapsedFields: documentRef.getElementById("editOverrideElapsedFields"),
  editCheckpointSoundToggleRow: documentRef.getElementById("editCheckpointSoundToggleRow"),
  editCheckpointSoundToggle: documentRef.getElementById("editCheckpointSoundToggle"),
  editCheckpointSoundModeField: documentRef.getElementById("editCheckpointSoundModeField"),
  editCheckpointSoundModeSelect: documentRef.getElementById("editCheckpointSoundModeSelect") as HTMLSelectElement | null,
  editCheckpointAlertsGroup: documentRef.getElementById("editCheckpointAlertsGroup"),
  editCheckpointToastToggleRow: documentRef.getElementById("editCheckpointToastToggleRow"),
  editCheckpointToastToggle: documentRef.getElementById("editCheckpointToastToggle"),
  editCheckpointToastModeField: documentRef.getElementById("editCheckpointToastModeField"),
  editCheckpointToastModeSelect: documentRef.getElementById("editCheckpointToastModeSelect") as HTMLSelectElement | null,
  editCheckpointAlertsNote: documentRef.getElementById("editCheckpointAlertsNote"),
  editTimerSettingsGroup: documentRef.getElementById("editTimerSettingsGroup"),
  editPresetIntervalsToggleRow: documentRef.getElementById("editPresetIntervalsToggleRow"),
  editPresetIntervalsToggle: documentRef.getElementById("editPresetIntervalsToggle"),
  editPresetIntervalsInfoBtn: documentRef.getElementById("editPresetIntervalsInfoBtn"),
  editPresetIntervalsInfoDialog: documentRef.getElementById("editPresetIntervalsInfoDialog"),
  editPresetIntervalField: documentRef.getElementById("editPresetIntervalField"),
  editPresetIntervalInput: documentRef.getElementById("editPresetIntervalInput") as HTMLInputElement | null,
  editPresetIntervalNote: documentRef.getElementById("editPresetIntervalNote"),
  editFinalCheckpointActionField: documentRef.getElementById("editFinalCheckpointActionField"),
  editFinalCheckpointActionSelect: documentRef.getElementById("editFinalCheckpointActionSelect") as HTMLSelectElement | null,
  editD: documentRef.getElementById("editD") as HTMLInputElement | null,
  editH: documentRef.getElementById("editH") as HTMLInputElement | null,
  editM: documentRef.getElementById("editM") as HTMLInputElement | null,
  editS: documentRef.getElementById("editS") as HTMLInputElement | null,
  msToggle: documentRef.getElementById("msToggle"),
  msArea: documentRef.getElementById("msArea"),
  msUnitRow: documentRef.getElementById("msUnitRow"),
  msUnitDay: documentRef.getElementById("msUnitDay"),
  msUnitHour: documentRef.getElementById("msUnitHour"),
  msUnitMinute: documentRef.getElementById("msUnitMinute"),
  msList: documentRef.getElementById("msList"),
  addMsBtn: documentRef.getElementById("addMsBtn"),
  cancelEditBtn: documentRef.getElementById("cancelEditBtn"),
  saveEditBtn: documentRef.getElementById("saveEditBtn") as HTMLButtonElement | null,
  editValidationError: documentRef.getElementById("editValidationError"),
  elapsedPadOverlay: documentRef.getElementById("elapsedPadOverlay"),
  elapsedPadTitle: documentRef.getElementById("elapsedPadTitle"),
  elapsedPadDisplay: documentRef.getElementById("elapsedPadDisplay"),
  elapsedPadError: documentRef.getElementById("elapsedPadError"),
  elapsedPadCancelBtn: documentRef.getElementById("elapsedPadCancelBtn"),
  elapsedPadDoneBtn: documentRef.getElementById("elapsedPadDoneBtn"),

  confirmOverlay: documentRef.getElementById("confirmOverlay"),
  confirmTitle: documentRef.getElementById("confirmTitle"),
  confirmText: documentRef.getElementById("confirmText"),
  confirmChkRow: documentRef.getElementById("confirmChkRow"),
  confirmDeleteAll: documentRef.getElementById("confirmDeleteAll") as HTMLInputElement | null,
  confirmChkNote: documentRef.getElementById("confirmChkNote"),
  confirmCancelBtn: documentRef.getElementById("confirmCancelBtn"),
  confirmOkBtn: documentRef.getElementById("confirmOkBtn"),
  confirmAltBtn: documentRef.getElementById("confirmAltBtn"),
  confirmChkLabel: documentRef.getElementById("confirmChkLabel"),
  timeGoalCompleteOverlay: documentRef.getElementById("timeGoalCompleteOverlay"),
  timeGoalCompleteTitle: documentRef.getElementById("timeGoalCompleteTitle"),
  timeGoalCompleteText: documentRef.getElementById("timeGoalCompleteText"),
  timeGoalCompleteMeta: documentRef.getElementById("timeGoalCompleteMeta"),
  timeGoalCompleteSaveBtn: documentRef.getElementById("timeGoalCompleteSaveBtn") as HTMLButtonElement | null,
  timeGoalCompleteDiscardBtn: documentRef.getElementById("timeGoalCompleteDiscardBtn") as HTMLButtonElement | null,
  timeGoalCompleteUpdateGoalBtn: documentRef.getElementById("timeGoalCompleteUpdateGoalBtn") as HTMLButtonElement | null,
  timeGoalCompleteGoalEditor: documentRef.getElementById("timeGoalCompleteGoalEditor"),
  timeGoalCompleteDurationValueInput: documentRef.getElementById("timeGoalCompleteDurationValueInput") as HTMLInputElement | null,
  timeGoalCompleteDurationUnitMinute: documentRef.getElementById("timeGoalCompleteDurationUnitMinute") as HTMLButtonElement | null,
  timeGoalCompleteDurationUnitHour: documentRef.getElementById("timeGoalCompleteDurationUnitHour") as HTMLButtonElement | null,
  timeGoalCompleteDurationPeriodDay: documentRef.getElementById("timeGoalCompleteDurationPeriodDay") as HTMLButtonElement | null,
  timeGoalCompleteDurationPeriodWeek: documentRef.getElementById("timeGoalCompleteDurationPeriodWeek") as HTMLButtonElement | null,
  timeGoalCompleteDurationReadout: documentRef.getElementById("timeGoalCompleteDurationReadout"),
  timeGoalCompleteContinueCancelBtn: documentRef.getElementById("timeGoalCompleteContinueCancelBtn") as HTMLButtonElement | null,
  timeGoalCompleteContinueConfirmBtn: documentRef.getElementById("timeGoalCompleteContinueConfirmBtn") as HTMLButtonElement | null,
  timeGoalCompleteSaveNoteOverlay: documentRef.getElementById("timeGoalCompleteSaveNoteOverlay"),
  timeGoalCompleteSaveNoteNoBtn: documentRef.getElementById("timeGoalCompleteSaveNoteNoBtn") as HTMLButtonElement | null,
  timeGoalCompleteSaveNoteYesBtn: documentRef.getElementById("timeGoalCompleteSaveNoteYesBtn") as HTMLButtonElement | null,
  timeGoalCompleteNoteOverlay: documentRef.getElementById("timeGoalCompleteNoteOverlay"),
  timeGoalCompleteNoteTitle: documentRef.getElementById("timeGoalCompleteNoteTitle"),
  timeGoalCompleteNoteText: documentRef.getElementById("timeGoalCompleteNoteText"),
  timeGoalCompleteNoteInput: documentRef.getElementById("timeGoalCompleteNoteInput") as HTMLTextAreaElement | null,
  timeGoalCompleteNoteDoneBtn: documentRef.getElementById("timeGoalCompleteNoteDoneBtn") as HTMLButtonElement | null,

  confirmChkRow2: documentRef.getElementById("confirmChkRow2"),
  confirmChkLabel2: documentRef.getElementById("confirmChkLabel2"),
  confirmLogChk: documentRef.getElementById("confirmLogChk") as HTMLInputElement | null,
  historyAnalysisOverlay: documentRef.getElementById("historyAnalysisOverlay"),
  historyAnalysisTitle: documentRef.getElementById("historyAnalysisTitle"),
  historyAnalysisSummary: documentRef.getElementById("historyAnalysisSummary"),
  historyEntryNoteOverlay: documentRef.getElementById("historyEntryNoteOverlay"),
  historyEntryNoteTitle: documentRef.getElementById("historyEntryNoteTitle"),
  historyEntryNoteMeta: documentRef.getElementById("historyEntryNoteMeta"),
  historyEntryNoteBody: documentRef.getElementById("historyEntryNoteBody"),

  historyScreen: documentRef.getElementById("historyScreen"),
  historyBackBtn: documentRef.getElementById("historyBackBtn"),
  historyTitle: documentRef.getElementById("historyTitle"),
  historyOlderBtn: documentRef.getElementById("historyOlderBtn") as HTMLButtonElement | null,
  historyNewerBtn: documentRef.getElementById("historyNewerBtn") as HTMLButtonElement | null,
  historyRangeText: documentRef.getElementById("historyRangeText"),
  historyCanvas: documentRef.getElementById("historyChart") as HTMLCanvasElement | null,
  historyCanvasWrap: documentRef.getElementById("historyCanvasWrap"),
  historyEditBtn: documentRef.getElementById("historyEditBtn"),
  historyDeleteBtn: documentRef.getElementById("historyDeleteBtn") as HTMLButtonElement | null,
  historyTrashRow: documentRef.getElementById("historyTrashRow"),
  checkpointToastHost: documentRef.getElementById("checkpointToastHost"),
};


  return els;
}

export type TaskTimerElements = ReturnType<typeof collectTaskTimerElements>;
