export function collectTaskTimerElements(documentRef: Document) {
const els = {
  taskList: documentRef.getElementById("taskList"),
  taskOrderByMenu: documentRef.getElementById("taskOrderByMenu") as HTMLDetailsElement | null,
  taskOrderByMenuBtn: documentRef.getElementById("taskOrderByMenuBtn") as HTMLElement | null,
  taskOrderByValue: documentRef.getElementById("taskOrderByValue"),
  openScheduleBtn: documentRef.getElementById("openScheduleBtn") as HTMLButtonElement | null,
  openAddTaskBtn: documentRef.getElementById("openAddTaskBtn"),
  closeScheduleBtn: documentRef.getElementById("closeScheduleBtn") as HTMLButtonElement | null,
  addTaskOverlay: documentRef.getElementById("addTaskOverlay"),
  addTaskForm: documentRef.getElementById("addTaskForm"),
  addTaskName: documentRef.getElementById("addTaskName") as HTMLInputElement | null,
  addTaskNameCombo: documentRef.getElementById("addTaskNameCombo"),
  addTaskNameToggle: documentRef.getElementById("addTaskNameToggle"),
  addTaskNameMenu: documentRef.getElementById("addTaskNameMenu"),
  addTaskNameCustomTitle: documentRef.getElementById("addTaskNameCustomTitle"),
  addTaskNameCustomList: documentRef.getElementById("addTaskNameCustomList"),
  addTaskNameDivider: documentRef.getElementById("addTaskNameDivider"),
  addTaskNamePresetTitle: documentRef.getElementById("addTaskNamePresetTitle"),
  addTaskNamePresetList: documentRef.getElementById("addTaskNamePresetList"),
  addTaskTypeRecurringBtn: documentRef.getElementById("addTaskTypeRecurringBtn") as HTMLButtonElement | null,
  addTaskTypeOnceOffBtn: documentRef.getElementById("addTaskTypeOnceOffBtn") as HTMLButtonElement | null,
  addTaskScheduleToggle: documentRef.getElementById("addTaskScheduleToggle") as HTMLInputElement | null,
  addTaskScheduleFields: documentRef.getElementById("addTaskScheduleFields"),
  addTaskOnceOffDayField: documentRef.getElementById("addTaskOnceOffDayField"),
  addTaskOnceOffDaySelect: documentRef.getElementById("addTaskOnceOffDaySelect") as HTMLSelectElement | null,
  addTaskPlannedStartHourSelect: documentRef.getElementById("addTaskPlannedStartHourSelect") as HTMLSelectElement | null,
  addTaskPlannedStartMinuteSelect: documentRef.getElementById("addTaskPlannedStartMinuteSelect") as HTMLSelectElement | null,
  addTaskPlannedStartMeridiemSelect: documentRef.getElementById("addTaskPlannedStartMeridiemSelect") as HTMLSelectElement | null,
  addTaskPlannedStartInput: documentRef.getElementById("addTaskPlannedStartInput") as HTMLInputElement | null,
  addTaskPlannedStartPushReminders: documentRef.getElementById("addTaskPlannedStartPushReminders") as HTMLInputElement | null,
  addTaskPlannedStartPushRemindersRow: documentRef.getElementById("addTaskPlannedStartPushRemindersRow"),
  addTaskDurationRow: documentRef.getElementById("addTaskDurationRow"),
  addTaskDurationValueInput: documentRef.getElementById("addTaskDurationValueInput") as HTMLInputElement | null,
  addTaskDurationUnitMinute: documentRef.getElementById("addTaskDurationUnitMinute") as HTMLButtonElement | null,
  addTaskDurationUnitHour: documentRef.getElementById("addTaskDurationUnitHour") as HTMLButtonElement | null,
  addTaskDurationPerLabel: documentRef.getElementById("addTaskDurationPerLabel"),
  addTaskDurationPeriodPills: documentRef.getElementById("addTaskDurationPeriodPills"),
  addTaskDurationPeriodDay: documentRef.getElementById("addTaskDurationPeriodDay") as HTMLButtonElement | null,
  addTaskDurationPeriodWeek: documentRef.getElementById("addTaskDurationPeriodWeek") as HTMLButtonElement | null,
  addTaskDurationReadout: documentRef.getElementById("addTaskDurationReadout"),
  addTaskTimeGoalToggleRow: documentRef.getElementById("addTaskTimeGoalToggleRow"),
  addTaskColorTrigger: documentRef.getElementById("addTaskColorTrigger") as HTMLButtonElement | null,
  addTaskColorPopover: documentRef.getElementById("addTaskColorPopover"),
  addTaskColorPalette: documentRef.getElementById("addTaskColorPalette"),
  addTaskColorNone: documentRef.getElementById("addTaskColorNone") as HTMLButtonElement | null,
  addTaskConfirmBtn: documentRef.getElementById("addTaskConfirmBtn"),
  addTaskError: documentRef.getElementById("addTaskError"),
  addTaskMsToggle: documentRef.getElementById("addTaskMsToggle") as HTMLInputElement | null,
  addTaskAddMsBtn: documentRef.getElementById("addTaskAddMsBtn") as HTMLButtonElement | null,
  addTaskMsArea: documentRef.getElementById("addTaskMsArea"),
  addTaskMsList: documentRef.getElementById("addTaskMsList"),
  addTaskAdvancedMenu: documentRef.getElementById("addTaskAdvancedMenu") as HTMLDetailsElement | null,
  addTaskCheckpointSoundModeField: documentRef.getElementById("addTaskCheckpointSoundModeField"),
  addTaskCheckpointSoundModeSelect: documentRef.getElementById("addTaskCheckpointSoundModeSelect") as HTMLSelectElement | null,
  addTaskCheckpointToastModeField: documentRef.getElementById("addTaskCheckpointToastModeField"),
  addTaskCheckpointToastModeSelect: documentRef.getElementById("addTaskCheckpointToastModeSelect") as HTMLSelectElement | null,
  addTaskFinalCheckpointActionField: documentRef.getElementById("addTaskFinalCheckpointActionField"),
  addTaskCancelBtn: documentRef.getElementById("addTaskCancelBtn"),
  resetAllBtn: documentRef.getElementById("resetAllBtn"),
  mode1View: documentRef.getElementById("mode1View"),
  appPageTasks: documentRef.getElementById("appPageTasks"),
  appPageSchedule: documentRef.getElementById("appPageSchedule"),
  appPageDashboard: documentRef.getElementById("appPageDashboard"),
  appPageFriends: documentRef.getElementById("appPageFriends"),
  appPageLeaderboard: documentRef.getElementById("appPageLeaderboard"),
  appPageHistory: documentRef.getElementById("appPageHistory"),
  scheduleGridScroller: documentRef.getElementById("scheduleGridScroller") as HTMLElement | null,
  scheduleGrid: documentRef.getElementById("scheduleGrid") as HTMLElement | null,
  scheduleTrayList: documentRef.getElementById("scheduleTrayList") as HTMLElement | null,
  scheduleMobileDayTabs: documentRef.getElementById("scheduleMobileDayTabs") as HTMLElement | null,
  appRoot: documentRef.getElementById("app"),
  groupsFriendsSection: documentRef.getElementById("groupsFriendsSection"),
  openFriendRequestModalBtn: documentRef.getElementById("openFriendRequestModalBtn") as HTMLButtonElement | null,
  friendRequestModal: documentRef.getElementById("friendRequestModal"),
  friendRequestEmailInput: documentRef.getElementById("friendRequestEmailInput") as HTMLInputElement | null,
  friendRequestCancelBtn: documentRef.getElementById("friendRequestCancelBtn") as HTMLButtonElement | null,
  friendRequestSendBtn: documentRef.getElementById("friendRequestSendBtn") as HTMLButtonElement | null,
  friendRequestModalStatus: documentRef.getElementById("friendRequestModalStatus"),
  friendProfileModal: documentRef.getElementById("friendProfileModal"),
  friendProfileAvatar: documentRef.getElementById("friendProfileAvatar") as HTMLImageElement | null,
  friendProfileName: documentRef.getElementById("friendProfileName"),
  friendProfileRankImage: documentRef.getElementById("friendProfileRankImage") as HTMLImageElement | null,
  friendProfileRankPlaceholder: documentRef.getElementById("friendProfileRankPlaceholder"),
  friendProfileRank: documentRef.getElementById("friendProfileRank"),
  friendProfileMemberSince: documentRef.getElementById("friendProfileMemberSince"),
  friendProfileDeleteBtn: documentRef.getElementById("friendProfileDeleteBtn") as HTMLButtonElement | null,
  friendProfileCloseBtn: documentRef.getElementById("friendProfileCloseBtn") as HTMLButtonElement | null,
  shareTaskModal: documentRef.getElementById("shareTaskModal"),
  shareTaskTitle: documentRef.getElementById("shareTaskTitle"),
  shareTaskScopeSelect: documentRef.getElementById("shareTaskScopeSelect") as HTMLSelectElement | null,
  shareTaskFriendsField: documentRef.getElementById("shareTaskFriendsField"),
  shareTaskFriendsList: documentRef.getElementById("shareTaskFriendsList"),
  shareTaskStatus: documentRef.getElementById("shareTaskStatus"),
  shareTaskCancelBtn: documentRef.getElementById("shareTaskCancelBtn") as HTMLButtonElement | null,
  shareTaskConfirmBtn: documentRef.getElementById("shareTaskConfirmBtn") as HTMLButtonElement | null,
  exportTaskOverlay: documentRef.getElementById("exportTaskOverlay"),
  exportTaskTitle: documentRef.getElementById("exportTaskTitle"),
  exportTaskIncludeHistoryRow: documentRef.getElementById("exportTaskIncludeHistoryRow"),
  exportTaskIncludeHistory: documentRef.getElementById("exportTaskIncludeHistory") as HTMLInputElement | null,
  exportTaskIncludeHistoryLabel: documentRef.getElementById("exportTaskIncludeHistoryLabel"),
  exportTaskCancelBtn: documentRef.getElementById("exportTaskCancelBtn") as HTMLButtonElement | null,
  exportTaskConfirmBtn: documentRef.getElementById("exportTaskConfirmBtn") as HTMLButtonElement | null,
  groupsIncomingRequestsList: documentRef.getElementById("groupsIncomingRequestsList"),
  groupsIncomingRequestsDetails: documentRef.getElementById("groupsIncomingRequestsDetails") as HTMLDetailsElement | null,
  groupsIncomingRequestsTitle: documentRef.getElementById("groupsIncomingRequestsTitle"),
  groupsOutgoingRequestsDetails: documentRef.getElementById("groupsOutgoingRequestsDetails") as HTMLDetailsElement | null,
  groupsOutgoingRequestsTitle: documentRef.getElementById("groupsOutgoingRequestsTitle"),
  groupsOutgoingRequestsList: documentRef.getElementById("groupsOutgoingRequestsList"),
  groupsFriendsList: documentRef.getElementById("groupsFriendsList"),
  groupsSharedByYouList: documentRef.getElementById("groupsSharedByYouList"),
  groupsSharedByYouTitle: documentRef.getElementById("groupsSharedByYouTitle"),
  groupsFriendRequestStatus: documentRef.getElementById("groupsFriendRequestStatus"),
  historySaveWorkingIndicator: documentRef.getElementById("historySaveWorkingIndicator"),
  historySaveWorkingText: documentRef.getElementById("historySaveWorkingText"),
  dashboardShellScene: documentRef.getElementById("dashboardShellScene"),
  dashboardShellContent: documentRef.getElementById("dashboardShellContent"),
  dashboardShellBack: documentRef.getElementById("dashboardShellBack"),
  dashboardRefreshBusyOverlay: documentRef.getElementById("dashboardRefreshBusyOverlay"),
  dashboardRefreshBusyText: documentRef.getElementById("dashboardRefreshBusyText"),
  initialAuthBusyOverlay: documentRef.getElementById("initialAuthBusyOverlay"),
  initialAuthBusyText: documentRef.getElementById("initialAuthBusyText"),
  footerTasksBtn: documentRef.getElementById("footerTasksBtn") as HTMLButtonElement | null,
  footerDashboardBtn: documentRef.getElementById("footerDashboardBtn") as HTMLButtonElement | null,
  footerTest2Btn: documentRef.getElementById("footerTest2Btn") as HTMLButtonElement | null,
  footerTest2AlertBadge: documentRef.getElementById("footerTest2AlertBadge") as HTMLElement | null,
  footerLeaderboardBtn: documentRef.getElementById("footerLeaderboardBtn") as HTMLButtonElement | null,
  footerSettingsBtn: documentRef.getElementById("footerSettingsBtn") as HTMLButtonElement | null,
  commandCenterTasksBtn: documentRef.getElementById("commandCenterTasksBtn") as HTMLButtonElement | null,
  commandCenterDashboardBtn: documentRef.getElementById("commandCenterDashboardBtn") as HTMLButtonElement | null,
  commandCenterGroupsBtn: documentRef.getElementById("commandCenterGroupsBtn") as HTMLButtonElement | null,
  commandCenterLeaderboardBtn: documentRef.getElementById("commandCenterLeaderboardBtn") as HTMLButtonElement | null,
  commandCenterHistoryBtn: documentRef.getElementById("commandCenterHistoryBtn") as HTMLButtonElement | null,
  commandCenterSettingsBtn: documentRef.getElementById("commandCenterSettingsBtn") as HTMLElement | null,
  rewardsInfoOpenBtn: documentRef.getElementById("rewardsInfoOpenBtn") as HTMLButtonElement | null,
  rewardsInfoOverlay: documentRef.getElementById("rewardsInfoOverlay") as HTMLElement | null,
  signedInHeaderBadge: documentRef.getElementById("signedInHeaderBadge") as HTMLElement | null,
  dashboardEditBtn: documentRef.getElementById("dashboardEditBtn") as HTMLButtonElement | null,
  dashboardEditCancelBtn: documentRef.getElementById("dashboardEditCancelBtn") as HTMLButtonElement | null,
  dashboardEditDoneBtn: documentRef.getElementById("dashboardEditDoneBtn") as HTMLButtonElement | null,
  dashboardRefreshBtn: documentRef.getElementById("dashboardRefreshBtn") as HTMLButtonElement | null,
  dashboardPanelMenuBtn: documentRef.getElementById("dashboardPanelMenuBtn") as HTMLElement | null,
  dashboardPanelMenuBackBtn: documentRef.getElementById("dashboardPanelMenuBackBtn") as HTMLButtonElement | null,
  dashboardPanelMenuList: documentRef.getElementById("dashboardPanelMenuList") as HTMLElement | null,
  dashboardGrid: documentRef.querySelector(".dashboardGrid") as HTMLElement | null,
  dashboardWeeklyGoalsValue: documentRef.getElementById("dashboardWeeklyGoalsValue"),
  dashboardWeeklyGoalsMeta: documentRef.getElementById("dashboardWeeklyGoalsMeta"),
  dashboardWeeklyGoalsProgressBar: documentRef.getElementById("dashboardWeeklyGoalsProgressBar"),
  dashboardWeeklyGoalsProjectionMarker: documentRef.getElementById("dashboardWeeklyGoalsProjectionMarker"),
  dashboardWeeklyGoalsProjectionFill: documentRef.getElementById("dashboardWeeklyGoalsProjectionFill"),
  dashboardWeeklyGoalsProgressFill: documentRef.getElementById("dashboardWeeklyGoalsProgressFill"),
  dashboardWeeklyGoalsProgressText: documentRef.getElementById("dashboardWeeklyGoalsProgressText"),
  dashboardMomentumCard: documentRef.querySelector('.dashboardCard[data-dashboard-id="momentum"]') as HTMLElement | null,
  dashboardMomentumDial: documentRef.getElementById("dashboardMomentumDial"),
  dashboardMomentumArcActive: documentRef.getElementById("dashboardMomentumArcActive"),
  dashboardMomentumNeedle: documentRef.getElementById("dashboardMomentumNeedle"),
  dashboardMomentumScoreValue: documentRef.getElementById("dashboardMomentumScoreValue"),
  dashboardMomentumScoreStatus: documentRef.getElementById("dashboardMomentumScoreStatus"),
  dashboardMomentumDrivers: documentRef.getElementById("dashboardMomentumDrivers"),
  dashboardMomentumFooterMessage: documentRef.getElementById("dashboardMomentumFooterMessage"),
  dashboardAvgSessionChart: documentRef.getElementById("dashboardAvgSessionChart") as HTMLCanvasElement | null,
  dashboardAvgSessionEmpty: documentRef.getElementById("dashboardAvgSessionEmpty"),
  dashboardAvgSessionTitle: documentRef.getElementById("dashboardAvgSessionTitle"),
  dashboardTimelineList: documentRef.getElementById("dashboardTimelineList"),
  dashboardTimelineNote: documentRef.getElementById("dashboardTimelineNote"),
  dashboardTimelineSummary: documentRef.getElementById("dashboardTimelineSummary"),
  dashboardFocusTrendCard: documentRef.getElementById("dashboardFocusTrendCard"),
  dashboardFocusTrendBars: documentRef.getElementById("dashboardFocusTrendBars"),
  dashboardFocusTrendAxis: documentRef.getElementById("dashboardFocusTrendAxis"),
  dashboardModeDonut: documentRef.getElementById("dashboardModeDonut"),
  dashboardModeDonutCenter: documentRef.getElementById("dashboardModeDonutCenter"),
  dashboardMode1Label: documentRef.getElementById("dashboardMode1Label"),
  dashboardMode2Label: documentRef.getElementById("dashboardMode2Label"),
  dashboardMode3Label: documentRef.getElementById("dashboardMode3Label"),
  dashboardMode1Value: documentRef.getElementById("dashboardMode1Value"),
  dashboardMode2Value: documentRef.getElementById("dashboardMode2Value"),
  dashboardMode3Value: documentRef.getElementById("dashboardMode3Value"),
  dashboardHeatCard: documentRef.getElementById("dashboardHeatCard"),
  dashboardHeatFaceFront: documentRef.getElementById("dashboardHeatFaceFront"),
  dashboardHeatFaceBack: documentRef.getElementById("dashboardHeatFaceBack"),
  dashboardHeatMonthLabel: documentRef.getElementById("dashboardHeatMonthLabel"),
  dashboardHeatWeekdays: documentRef.getElementById("dashboardHeatWeekdays"),
  dashboardHeatCalendarGrid: documentRef.getElementById("dashboardHeatCalendarGrid"),
  dashboardHeatSummaryDate: documentRef.getElementById("dashboardHeatSummaryDate"),
  dashboardHeatSummaryBody: documentRef.getElementById("dashboardHeatSummaryBody"),
  dashboardHeatSummaryCloseBtn: documentRef.getElementById("dashboardHeatSummaryCloseBtn") as HTMLButtonElement | null,

  menuIcon: documentRef.getElementById("menuIcon"),
  historyManagerScreen: documentRef.getElementById("historyManagerScreen"),
  historyManagerLoadingOverlay: documentRef.getElementById("historyManagerLoadingOverlay") as HTMLElement | null,
  historyManagerBtn: documentRef.getElementById("historyManagerBtn"),
  historyManagerExportBtn: documentRef.getElementById("historyManagerExportBtn") as HTMLButtonElement | null,
  historyManagerImportBtn: documentRef.getElementById("historyManagerImportBtn") as HTMLButtonElement | null,
  historyManagerGenerateBtn: documentRef.getElementById("historyManagerGenerateBtn") as HTMLButtonElement | null,
  historyManagerImportFile: documentRef.getElementById("historyManagerImportFile") as HTMLInputElement | null,
  historyManagerBulkBtn: documentRef.getElementById("historyManagerBulkBtn") as HTMLButtonElement | null,
  historyManagerBulkDeleteBtn: documentRef.getElementById("historyManagerBulkDeleteBtn") as HTMLButtonElement | null,
  historyManagerBackBtn: documentRef.getElementById("historyManagerBackBtn"),
  historyManagerManualEntryOverlay: documentRef.getElementById("historyManagerManualEntryOverlay") as HTMLElement | null,
  historyManagerManualEntryTitle: documentRef.getElementById("historyManagerManualEntryTitle"),
  historyManagerManualEntryMeta: documentRef.getElementById("historyManagerManualEntryMeta"),
  historyManagerManualDateTimeInput: documentRef.getElementById("historyManagerManualDateTimeInput") as HTMLInputElement | null,
  historyManagerManualDateTimeBtn: documentRef.getElementById("historyManagerManualDateTimeBtn") as HTMLButtonElement | null,
  historyManagerManualHoursInput: documentRef.getElementById("historyManagerManualHoursInput") as HTMLInputElement | null,
  historyManagerManualMinutesInput: documentRef.getElementById("historyManagerManualMinutesInput") as HTMLInputElement | null,
  historyManagerManualEntryDifficultyGroup: documentRef.getElementById("historyManagerManualEntryDifficultyGroup"),
  historyManagerManualNoteInput: documentRef.getElementById("historyManagerManualNoteInput") as HTMLInputElement | null,
  historyManagerManualEntryError: documentRef.getElementById("historyManagerManualEntryError"),
  historyManagerManualEntryCancelBtn: documentRef.getElementById("historyManagerManualEntryCancelBtn") as HTMLButtonElement | null,
  historyManagerManualEntrySaveBtn: documentRef.getElementById("historyManagerManualEntrySaveBtn") as HTMLButtonElement | null,
  taskManualEntryOverlay: documentRef.getElementById("taskManualEntryOverlay") as HTMLElement | null,
  taskManualEntryTitle: documentRef.getElementById("taskManualEntryTitle"),
  taskManualEntryMeta: documentRef.getElementById("taskManualEntryMeta"),
  taskManualDateTimeInput: documentRef.getElementById("taskManualDateTimeInput") as HTMLInputElement | null,
  taskManualDateTimeBtn: documentRef.getElementById("taskManualDateTimeBtn") as HTMLButtonElement | null,
  taskManualHoursInput: documentRef.getElementById("taskManualHoursInput") as HTMLInputElement | null,
  taskManualMinutesInput: documentRef.getElementById("taskManualMinutesInput") as HTMLInputElement | null,
  taskManualEntryDifficultyGroup: documentRef.getElementById("taskManualEntryDifficultyGroup"),
  taskManualNoteInput: documentRef.getElementById("taskManualNoteInput") as HTMLInputElement | null,
  taskManualEntryError: documentRef.getElementById("taskManualEntryError"),
  taskManualEntryCancelBtn: documentRef.getElementById("taskManualEntryCancelBtn") as HTMLButtonElement | null,
  taskManualEntrySaveBtn: documentRef.getElementById("taskManualEntrySaveBtn") as HTMLButtonElement | null,
  focusModeScreen: documentRef.getElementById("focusModeScreen"),
  focusModeBackBtn: documentRef.getElementById("focusModeBackBtn"),
  focusDial: documentRef.getElementById("focusDial"),
  focusCheckpointRing: documentRef.getElementById("focusCheckpointRing"),
  focusCheckpointToggle: documentRef.getElementById("focusCheckpointToggle"),
  focusCheckpointLog: documentRef.getElementById("focusCheckpointLog"),
  focusCheckpointLogEmpty: documentRef.getElementById("focusCheckpointLogEmpty"),
  focusCheckpointLogList: documentRef.getElementById("focusCheckpointLogList"),
  focusSessionNotesSection: documentRef.getElementById("focusSessionNotesSection") as HTMLElement | null,
  focusTaskName: documentRef.getElementById("focusTaskName"),
  focusTimerDays: documentRef.getElementById("focusTimerDays"),
  focusTimerClock: documentRef.getElementById("focusTimerClock"),
  focusDialHint: documentRef.getElementById("focusDialHint"),
  focusResetBtn: documentRef.getElementById("focusResetBtn") as HTMLButtonElement | null,
  focusInsightBest: documentRef.getElementById("focusInsightBest"),
  focusInsightWeekday: documentRef.getElementById("focusInsightWeekday"),
  focusInsightTodayDelta: documentRef.getElementById("focusInsightTodayDelta"),
  focusInsightWeekDelta: documentRef.getElementById("focusInsightWeekDelta"),
  focusInsightDifficulty: documentRef.getElementById("focusInsightDifficulty"),
  focusInsightProductivityPeriod: documentRef.getElementById("focusInsightProductivityPeriod"),
  focusSessionNotesInput: documentRef.getElementById("focusSessionNotesInput") as HTMLTextAreaElement | null,
  focusSessionNotesSavedText: documentRef.getElementById("focusSessionNotesSavedText"),
  hmList: documentRef.getElementById("hmList"),
  closeMenuBtn: documentRef.getElementById("closeMenuBtn"),

  aboutOverlay: documentRef.getElementById("aboutOverlay"),
  howtoOverlay: documentRef.getElementById("howtoOverlay"),
  appearanceOverlay: documentRef.getElementById("appearanceOverlay"),
  taskSettingsOverlay: documentRef.getElementById("taskSettingsOverlay"),
  taskWeekStartingSelect: documentRef.getElementById("taskWeekStartingSelect") as HTMLSelectElement | null,
  taskStartupModuleSelect: documentRef.getElementById("taskStartupModuleSelect") as HTMLSelectElement | null,
  taskAutoFocusOnLaunchToggleRow: documentRef.getElementById("taskAutoFocusOnLaunchToggleRow"),
  taskAutoFocusOnLaunchToggle: documentRef.getElementById("taskAutoFocusOnLaunchToggle"),
  taskDynamicColorsToggleRow: documentRef.getElementById("taskDynamicColorsToggleRow"),
  taskDynamicColorsToggle: documentRef.getElementById("taskDynamicColorsToggle"),
  taskMobilePushAlertsToggleRow: documentRef.getElementById("taskMobilePushAlertsToggleRow"),
  taskMobilePushAlertsToggle: documentRef.getElementById("taskMobilePushAlertsToggle"),
  taskWebPushAlertsToggleRow: documentRef.getElementById("taskWebPushAlertsToggleRow"),
  taskWebPushAlertsToggle: documentRef.getElementById("taskWebPushAlertsToggle"),
  taskCheckpointSoundToggleRow: documentRef.getElementById("taskCheckpointSoundToggleRow"),
  taskCheckpointSoundToggle: documentRef.getElementById("taskCheckpointSoundToggle"),
  taskCheckpointToastToggleRow: documentRef.getElementById("taskCheckpointToastToggleRow"),
  taskCheckpointToastToggle: documentRef.getElementById("taskCheckpointToastToggle"),
  taskCheckpointSoundModeField: documentRef.getElementById("taskCheckpointSoundModeField"),
  taskCheckpointSoundModeSelect: documentRef.getElementById("taskCheckpointSoundModeSelect") as HTMLSelectElement | null,
  taskCheckpointToastModeField: documentRef.getElementById("taskCheckpointToastModeField"),
  taskCheckpointToastModeSelect: documentRef.getElementById("taskCheckpointToastModeSelect") as HTMLSelectElement | null,
  optimalProductivityPeriodRow: documentRef.getElementById("optimalProductivityPeriodRow"),
  optimalProductivityStartTimeInput: documentRef.getElementById("optimalProductivityStartTimeInput") as HTMLInputElement | null,
  optimalProductivityEndTimeInput: documentRef.getElementById("optimalProductivityEndTimeInput") as HTMLInputElement | null,
  taskSettingsSaveBtn: documentRef.getElementById("taskSettingsSaveBtn"),
  preferencesLoadDefaultsBtn: documentRef.getElementById("preferencesLoadDefaultsBtn"),
  appearanceLoadDefaultsBtn: documentRef.getElementById("appearanceLoadDefaultsBtn"),
  themeToggleRow: documentRef.getElementById("themeToggleRow"),
  themeSelect: documentRef.getElementById("themeSelect") as HTMLSelectElement | null,
  themePurpleBtn: documentRef.getElementById("themePurpleBtn") as HTMLButtonElement | null,
  themeCyanBtn: documentRef.getElementById("themeCyanBtn") as HTMLButtonElement | null,
  themeLimeBtn: documentRef.getElementById("themeLimeBtn") as HTMLButtonElement | null,
  menuButtonStyleSelect: documentRef.getElementById("menuButtonStyleSelect") as HTMLSelectElement | null,
  menuButtonStyleParallelogramBtn: documentRef.getElementById("menuButtonStyleParallelogramBtn") as HTMLButtonElement | null,
  menuButtonStyleSquareBtn: documentRef.getElementById("menuButtonStyleSquareBtn") as HTMLButtonElement | null,
  contactOverlay: documentRef.getElementById("contactOverlay"),

  exportBtn: documentRef.getElementById("exportBtn"),
  importBtn: documentRef.getElementById("importBtn"),
  importFile: documentRef.getElementById("importFile") as HTMLInputElement | null,

  editOverlay: documentRef.getElementById("editOverlay"),
  editName: documentRef.getElementById("editName") as HTMLInputElement | null,
  editTaskTypeRecurringBtn: documentRef.getElementById("editTaskTypeRecurringBtn") as HTMLButtonElement | null,
  editTaskTypeOnceOffBtn: documentRef.getElementById("editTaskTypeOnceOffBtn") as HTMLButtonElement | null,
  editTaskScheduleToggle: documentRef.getElementById("editTaskScheduleToggle") as HTMLInputElement | null,
  editTaskScheduleFields: documentRef.getElementById("editTaskScheduleFields"),
  editTaskOnceOffDayField: documentRef.getElementById("editTaskOnceOffDayField"),
  editTaskOnceOffDaySelect: documentRef.getElementById("editTaskOnceOffDaySelect") as HTMLSelectElement | null,
  editPlannedStartHourSelect: documentRef.getElementById("editPlannedStartHourSelect") as HTMLSelectElement | null,
  editPlannedStartMinuteSelect: documentRef.getElementById("editPlannedStartMinuteSelect") as HTMLSelectElement | null,
  editPlannedStartMeridiemSelect: documentRef.getElementById("editPlannedStartMeridiemSelect") as HTMLSelectElement | null,
  editPlannedStartInput: documentRef.getElementById("editPlannedStartInput") as HTMLInputElement | null,
  editPlannedStartPushReminders: documentRef.getElementById("editPlannedStartPushReminders") as HTMLInputElement | null,
  editPlannedStartPushRemindersRow: documentRef.getElementById("editPlannedStartPushRemindersRow"),
  editTaskDurationRow: documentRef.getElementById("editTaskDurationRow"),
  editTaskDurationValueInput: documentRef.getElementById("editTaskDurationValueInput") as HTMLInputElement | null,
  editTaskDurationUnitMinute: documentRef.getElementById("editTaskDurationUnitMinute") as HTMLButtonElement | null,
  editTaskDurationUnitHour: documentRef.getElementById("editTaskDurationUnitHour") as HTMLButtonElement | null,
  editTaskDurationPeriodDay: documentRef.getElementById("editTaskDurationPeriodDay") as HTMLButtonElement | null,
  editTaskDurationPeriodWeek: documentRef.getElementById("editTaskDurationPeriodWeek") as HTMLButtonElement | null,
  editTaskDurationReadout: documentRef.getElementById("editTaskDurationReadout"),
  editTimeGoalToggleRow: documentRef.getElementById("editTaskTimeGoalToggleRow"),
  editTaskColorTrigger: documentRef.getElementById("editTaskColorTrigger") as HTMLButtonElement | null,
  editTaskColorPopover: documentRef.getElementById("editTaskColorPopover"),
  editTaskColorPalette: documentRef.getElementById("editTaskColorPalette"),
  editTaskColorNone: documentRef.getElementById("editTaskColorNone") as HTMLButtonElement | null,
  editMoveMenu: documentRef.getElementById("editMoveMenu") as HTMLDetailsElement | null,
  editMoveCurrentLabel: documentRef.getElementById("editMoveCurrentLabel"),
  editMoveMode1: documentRef.getElementById("editMoveMode1") as HTMLButtonElement | null,
  editMoveMode2: documentRef.getElementById("editMoveMode2") as HTMLButtonElement | null,
  editMoveMode3: documentRef.getElementById("editMoveMode3") as HTMLButtonElement | null,
  editCheckpointSoundToggleRow: documentRef.getElementById("editCheckpointSoundToggleRow"),
  editCheckpointSoundToggle: documentRef.getElementById("editCheckpointSoundToggle"),
  editCheckpointSoundModeField: documentRef.getElementById("editCheckpointSoundModeField"),
  editCheckpointSoundModeSelect: documentRef.getElementById("editCheckpointSoundModeSelect") as HTMLSelectElement | null,
  editCheckpointAlertsGroup: documentRef.getElementById("editCheckpointAlertsGroup"),
  editCheckpointToastToggleRow: documentRef.getElementById("editCheckpointToastToggleRow"),
  editCheckpointToastToggle: documentRef.getElementById("editCheckpointToastToggle"),
  editCheckpointToastModeField: documentRef.getElementById("editCheckpointToastModeField"),
  editCheckpointToastModeSelect: documentRef.getElementById("editCheckpointToastModeSelect") as HTMLSelectElement | null,
  editCheckpointAlertsNote: documentRef.getElementById("editCheckpointAlertsNote"),
  editTimerSettingsGroup: documentRef.getElementById("editTimerSettingsGroup"),
  editFinalCheckpointActionField: documentRef.getElementById("editFinalCheckpointActionField"),
  msToggle: documentRef.getElementById("msToggle"),
  msArea: documentRef.getElementById("msArea"),
  msList: documentRef.getElementById("msList"),
  addMsBtn: documentRef.getElementById("addMsBtn") as HTMLButtonElement | null,
  cancelEditBtn: documentRef.getElementById("cancelEditBtn"),
  saveEditBtn: documentRef.getElementById("saveEditBtn") as HTMLButtonElement | null,
  editValidationError: documentRef.getElementById("editValidationError"),
  elapsedPadOverlay: documentRef.getElementById("elapsedPadOverlay"),
  elapsedPadTitle: documentRef.getElementById("elapsedPadTitle"),
  elapsedPadDisplay: documentRef.getElementById("elapsedPadDisplay"),
  elapsedPadError: documentRef.getElementById("elapsedPadError"),
  elapsedPadUnitHourBtn: documentRef.getElementById("elapsedPadUnitHourBtn") as HTMLButtonElement | null,
  elapsedPadUnitMinuteBtn: documentRef.getElementById("elapsedPadUnitMinuteBtn") as HTMLButtonElement | null,
  elapsedPadCancelBtn: documentRef.getElementById("elapsedPadCancelBtn"),
  elapsedPadDoneBtn: documentRef.getElementById("elapsedPadDoneBtn"),

  confirmOverlay: documentRef.getElementById("confirmOverlay"),
  confirmTitle: documentRef.getElementById("confirmTitle"),
  confirmText: documentRef.getElementById("confirmText"),
  confirmChkRow: documentRef.getElementById("confirmChkRow"),
  confirmDeleteAll: documentRef.getElementById("confirmDeleteAll") as HTMLInputElement | null,
  confirmChkNote: documentRef.getElementById("confirmChkNote"),
  confirmCancelBtn: documentRef.getElementById("confirmCancelBtn"),
  confirmOkBtn: documentRef.getElementById("confirmOkBtn"),
  confirmAltBtn: documentRef.getElementById("confirmAltBtn"),
  confirmChkLabel: documentRef.getElementById("confirmChkLabel"),
  timeGoalCompleteOverlay: documentRef.getElementById("timeGoalCompleteOverlay"),
  timeGoalCompleteConfettiStage: documentRef.getElementById("timeGoalCompleteConfettiStage") as HTMLElement | null,
  timeGoalCompleteTitle: documentRef.getElementById("timeGoalCompleteTitle"),
  timeGoalCompleteText: documentRef.getElementById("timeGoalCompleteText"),
  timeGoalCompleteMeta: documentRef.getElementById("timeGoalCompleteMeta"),
  timeGoalCompleteDifficultyGroup: documentRef.getElementById("timeGoalCompleteDifficultyGroup"),
  timeGoalCompleteValidation: documentRef.getElementById("timeGoalCompleteValidation"),
  timeGoalCompleteAddNoteBtn: documentRef.getElementById("timeGoalCompleteAddNoteBtn") as HTMLButtonElement | null,
  timeGoalCompleteNextTasks: documentRef.getElementById("timeGoalCompleteNextTasks") as HTMLElement | null,
  timeGoalCompleteNextTaskGrid: documentRef.getElementById("timeGoalCompleteNextTaskGrid") as HTMLElement | null,
  timeGoalCompleteCloseBtn: documentRef.getElementById("timeGoalCompleteCloseBtn") as HTMLButtonElement | null,
  timeGoalCompleteLaunchNextBtn: documentRef.getElementById("timeGoalCompleteLaunchNextBtn") as HTMLButtonElement | null,
  timeGoalCompleteSaveNoteOverlay: documentRef.getElementById("timeGoalCompleteSaveNoteOverlay"),
  timeGoalCompleteSaveNoteNoBtn: documentRef.getElementById("timeGoalCompleteSaveNoteNoBtn") as HTMLButtonElement | null,
  timeGoalCompleteSaveNoteYesBtn: documentRef.getElementById("timeGoalCompleteSaveNoteYesBtn") as HTMLButtonElement | null,
  timeGoalCompleteNoteOverlay: documentRef.getElementById("timeGoalCompleteNoteOverlay"),
  timeGoalCompleteNoteTitle: documentRef.getElementById("timeGoalCompleteNoteTitle"),
  timeGoalCompleteNoteText: documentRef.getElementById("timeGoalCompleteNoteText"),
  timeGoalCompleteNoteInput: documentRef.getElementById("timeGoalCompleteNoteInput") as HTMLTextAreaElement | null,
  timeGoalCompleteNoteDoneBtn: documentRef.getElementById("timeGoalCompleteNoteDoneBtn") as HTMLButtonElement | null,
  rankPromotionOverlay: documentRef.getElementById("rankPromotionOverlay"),
  rankPromotionConfettiStage: documentRef.getElementById("rankPromotionConfettiStage") as HTMLElement | null,
  rankPromotionText: documentRef.getElementById("rankPromotionText"),
  rankPromotionCloseBtn: documentRef.getElementById("rankPromotionCloseBtn") as HTMLButtonElement | null,

  confirmChkRow2: documentRef.getElementById("confirmChkRow2"),
  confirmChkLabel2: documentRef.getElementById("confirmChkLabel2"),
  confirmLogChk: documentRef.getElementById("confirmLogChk") as HTMLInputElement | null,
  confirmDangerInputRow: documentRef.getElementById("confirmDangerInputRow"),
  confirmDangerInputLabel: documentRef.getElementById("confirmDangerInputLabel"),
  confirmDangerInput: documentRef.getElementById("confirmDangerInput") as HTMLInputElement | null,
  historyAnalysisOverlay: documentRef.getElementById("historyAnalysisOverlay"),
  historyAnalysisTitle: documentRef.getElementById("historyAnalysisTitle"),
  historyAnalysisSummary: documentRef.getElementById("historyAnalysisSummary"),
  historyEntryNoteOverlay: documentRef.getElementById("historyEntryNoteOverlay"),
  historyEntryNoteTitle: documentRef.getElementById("historyEntryNoteTitle"),
  historyEntryNoteMeta: documentRef.getElementById("historyEntryNoteMeta"),
  historyEntryNoteBody: documentRef.getElementById("historyEntryNoteBody"),
  historyEntryNoteEditor: documentRef.getElementById("historyEntryNoteEditor"),
  historyEntryNoteInput: documentRef.getElementById("historyEntryNoteInput") as HTMLTextAreaElement | null,
  historyEntryNoteEditBtn: documentRef.getElementById("historyEntryNoteEditBtn") as HTMLButtonElement | null,
  historyEntryNoteCancelBtn: documentRef.getElementById("historyEntryNoteCancelBtn") as HTMLButtonElement | null,
  historyEntryNoteSaveBtn: documentRef.getElementById("historyEntryNoteSaveBtn") as HTMLButtonElement | null,

  historyScreen: documentRef.getElementById("historyScreen"),
  historyBackBtn: documentRef.getElementById("historyBackBtn"),
  historyTitle: documentRef.getElementById("historyTitle"),
  historyOlderBtn: documentRef.getElementById("historyOlderBtn") as HTMLButtonElement | null,
  historyNewerBtn: documentRef.getElementById("historyNewerBtn") as HTMLButtonElement | null,
  historyRangeText: documentRef.getElementById("historyRangeText"),
  historyCanvas: documentRef.getElementById("historyChart") as HTMLCanvasElement | null,
  historyCanvasWrap: documentRef.getElementById("historyCanvasWrap"),
  historyEditBtn: documentRef.getElementById("historyEditBtn"),
  historyDeleteBtn: documentRef.getElementById("historyDeleteBtn") as HTMLButtonElement | null,
  historyTrashRow: documentRef.getElementById("historyTrashRow"),
  checkpointToastHost: documentRef.getElementById("checkpointToastHost"),
  cloudSyncNoticeHost: documentRef.getElementById("cloudSyncNoticeHost"),
};


  return els;
}

export type TaskTimerElements = ReturnType<typeof collectTaskTimerElements>;
