import type { AppPage, MainMode, TaskTimerMutableState } from "./types";
import { DEFAULT_REWARD_PROGRESS } from "../lib/rewards";

type TaskTimerStorageKeys = {
  AUTO_FOCUS_ON_TASK_LAUNCH_KEY: string;
  THEME_KEY: string;
  MENU_BUTTON_STYLE_KEY: string;
  WEEK_STARTING_KEY: string;
  STARTUP_MODULE_KEY: string;
  TASK_VIEW_KEY: string;
  TASK_ORDER_BY_KEY: string;
  DYNAMIC_COLORS_KEY: string;
  MOBILE_PUSH_ALERTS_KEY: string;
  WEB_PUSH_ALERTS_KEY: string;
  CHECKPOINT_ALERT_SOUND_KEY: string;
  CHECKPOINT_ALERT_TOAST_KEY: string;
  OPTIMAL_PRODUCTIVITY_START_TIME_KEY: string;
  OPTIMAL_PRODUCTIVITY_END_TIME_KEY: string;
  OPTIMAL_PRODUCTIVITY_DAYS_KEY: string;
  NAV_STACK_KEY: string;
  FOCUS_SESSION_NOTES_KEY: string;
  NAV_STACK_MAX: number;
  NATIVE_BACK_DEBOUNCE_MS: number;
};

export const DEFAULT_MODE_COLORS: Record<MainMode, string> = {
  mode1: "#00CFC8",
};

export function createTaskTimerStorageKeys(storageKey: string): TaskTimerStorageKeys {
  return {
    AUTO_FOCUS_ON_TASK_LAUNCH_KEY: `${storageKey}:autoFocusOnTaskLaunchEnabled`,
    THEME_KEY: `${storageKey}:theme`,
    MENU_BUTTON_STYLE_KEY: `${storageKey}:menuButtonStyle`,
    WEEK_STARTING_KEY: `${storageKey}:weekStarting`,
    STARTUP_MODULE_KEY: `${storageKey}:startupModule`,
    TASK_VIEW_KEY: `${storageKey}:taskView`,
    TASK_ORDER_BY_KEY: `${storageKey}:taskOrderBy`,
    DYNAMIC_COLORS_KEY: `${storageKey}:dynamicColorsEnabled`,
    MOBILE_PUSH_ALERTS_KEY: `${storageKey}:mobilePushAlertsEnabled`,
    WEB_PUSH_ALERTS_KEY: `${storageKey}:webPushAlertsEnabled`,
    CHECKPOINT_ALERT_SOUND_KEY: `${storageKey}:checkpointAlertSoundEnabled`,
    CHECKPOINT_ALERT_TOAST_KEY: `${storageKey}:checkpointAlertToastEnabled`,
    OPTIMAL_PRODUCTIVITY_START_TIME_KEY: `${storageKey}:optimalProductivityStartTime`,
    OPTIMAL_PRODUCTIVITY_END_TIME_KEY: `${storageKey}:optimalProductivityEndTime`,
    OPTIMAL_PRODUCTIVITY_DAYS_KEY: `${storageKey}:optimalProductivityDays`,
    NAV_STACK_KEY: `${storageKey}:navStack`,
    FOCUS_SESSION_NOTES_KEY: `${storageKey}:focusSessionNotes`,
    NAV_STACK_MAX: 50,
    NATIVE_BACK_DEBOUNCE_MS: 200,
  };
}

export function createInitialTaskTimerState(initialAppPage: AppPage): TaskTimerMutableState {
  return {
    deletedTaskMeta: {},
    tasks: [],
    editIndex: null,
    editDraftSnapshot: "",
    focusCheckpointSig: "",
    focusModeTaskName: "",
    focusShowCheckpoints: true,
    suppressAddTaskNameFocusOpen: false,
    confirmAction: null,
    confirmActionAlt: null,
    confirmActionCancel: null,
    themeMode: "lime",
    menuButtonStyle: "square",
    addTaskCustomNames: [],
    weekStarting: "mon",
    startupModule: "dashboard",
    taskView: "tile",
    taskOrderBy: "custom",
    dynamicColorsEnabled: true,
    autoFocusOnTaskLaunchEnabled: false,
    mobilePushAlertsEnabled: false,
    webPushAlertsEnabled: false,
    checkpointAlertSoundEnabled: true,
    checkpointAlertToastEnabled: true,
    checkpointAlertSoundMode: "once",
    checkpointAlertToastMode: "auto5s",
    optimalProductivityStartTime: "00:00",
    optimalProductivityEndTime: "23:59",
    optimalProductivityDays: ["sun", "mon", "tue", "wed", "thu", "fri", "sat"],
    rewardProgress: DEFAULT_REWARD_PROGRESS,
    historyByTaskId: {},
    liveSessionsByTaskId: {},
    historyRangeDaysByTaskId: {},
    historyRangeModeByTaskId: {},
    focusModeTaskId: null,
    openHistoryTaskIds: new Set(),
    pinnedHistoryTaskIds: new Set(),
    hmExpandedTaskGroups: new Set(),
    hmExpandedDateGroups: new Set(),
    hmSortKey: "ts",
    hmSortDir: "desc",
    hmBulkEditMode: false,
    hmBulkSelectedRows: new Set(),
    hmRowsByTask: {},
    hmRowsByTaskDate: {},
    historyViewByTaskId: {},
    addTaskMilestonesEnabled: false,
    addTaskMilestoneTimeUnit: "hour",
    addTaskMilestones: [],
    addTaskCheckpointSoundEnabled: false,
    addTaskCheckpointSoundMode: "once",
    addTaskCheckpointToastEnabled: false,
    addTaskCheckpointToastMode: "auto5s",
    timeGoalModalTaskId: null,
    timeGoalModalFrozenElapsedMs: 0,
    timeGoalReminderAtMsByTaskId: {},
    addTaskWizardStep: 1,
    addTaskType: "recurring",
    addTaskOnceOffDay: "mon",
    addTaskPlannedStartTime: "09:00",
    addTaskDurationValue: 5,
    addTaskDurationUnit: "hour",
    addTaskDurationPeriod: "day",
    focusSessionNotesByTaskId: {},
    addTaskNoTimeGoal: false,
    elapsedPadTarget: null,
    elapsedPadMilestoneRef: null,
    elapsedPadDraft: "",
    elapsedPadOriginal: "",
    dashboardEditMode: false,
    dashboardDragEl: null,
    taskDragEl: null,
    dashboardOrderDraftBeforeEdit: null,
    dashboardCardPlacements: {},
    dashboardCardPlacementsDraftBeforeEdit: null,
    dashboardCardSizes: {},
    dashboardCardSizesDraftBeforeEdit: null,
    dashboardCardVisibility: {},
    dashboardAvgRange: "past7",
    dashboardTimelineDensity: "medium",
    dashboardMenuFlipped: false,
    currentAppPage: initialAppPage,
    currentTileColumnCount: 1,
    suppressNavStackPush: false,
    lastNativeBackHandledAtMs: 0,
    checkpointToastQueue: [],
    activeCheckpointToast: null,
    checkpointBeepAudio: null,
    checkpointBeepQueueCount: 0,
    checkpointRepeatStopAtMs: 0,
    checkpointRepeatActiveTaskId: null,
    checkpointAutoResetDirty: false,
    historyNoteCloudRepairAttempted: false,
    checkpointFiredKeysByTaskId: {},
    checkpointBaselineSecByTaskId: {},
    cloudPreferencesCache: null,
    cloudDashboardCache: null,
    cloudTaskUiCache: null,
    navStackMemory: [],
    pendingTaskJumpMemory: null,
    groupsIncomingRequests: [],
    groupsOutgoingRequests: [],
    groupsFriendships: [],
    groupsSharedSummaries: [],
    ownSharedSummaries: [],
    shareTaskIndex: null,
    shareTaskMode: "share",
    shareTaskTaskId: null,
    exportTaskIndex: null,
    groupsLoading: false,
    groupsLoadingDepth: 0,
    groupsRefreshSeq: 0,
    activeFriendProfileUid: null,
    activeFriendProfileName: "",
    historyEntryNoteAnchorTaskId: "",
    openFriendSharedTaskUids: new Set(),
    workingIndicatorStack: [],
    workingIndicatorKeySeq: 0,
    workingIndicatorOverlayActive: false,
    workingIndicatorRestoreFocusEl: null,
    dashboardBusyStack: [],
    dashboardBusyKeySeq: 0,
    dashboardBusyOverlayActive: false,
    dashboardBusyRestoreFocusEl: null,
    dashboardBusyShownAtMs: 0,
    dashboardBusyHideTimer: null,
    initialAuthHydrating: true,
    friendProfileCacheByUid: {},
    cloudRefreshInFlight: null,
    lastCloudRefreshAtMs: 0,
    pendingDeferredCloudRefresh: false,
    lastUiInteractionAtMs: 0,
    dashboardWidgetHasRenderedData: {
      tasksCompleted: false,
      momentum: false,
      focusTrend: false,
      heatCalendar: false,
      modeDistribution: false,
      avgSession: false,
      timeline: false,
    },
  };
}
