import type { HistoryByTaskId, DeletedTaskMeta, LiveSessionsByTaskId, Task } from "../lib/types";
import type { FriendProfile, FriendRequest, Friendship, SharedTaskSummary } from "../lib/friendsStore";
import type { DashboardWeekStart } from "../lib/historyChart";
import type { StartupModulePreference } from "../lib/startupModule";

export type AppPage = "tasks" | "schedule" | "dashboard" | "friends" | "leaderboard" | "history";
export type MainMode = "mode1";

export type TaskTimerClientHandle = {
  destroy: () => void;
};

export type HistoryBarRect = {
  x: number;
  y: number;
  w: number;
  h: number;
  absIndex: number;
  hitX?: number;
  hitY?: number;
  hitW?: number;
  hitH?: number;
};

export type HistoryLabelHitRect = {
  x: number;
  y: number;
  w: number;
  h: number;
  absIndex: number;
};

export type HistoryViewState = {
  page: number;
  rangeDays: 7 | 14;
  rangeMode: "entries" | "day";
  revealPhase: "opening" | "open" | "closing";
  revealTimer: number | null;
  layoutRetryRaf: number | null;
  editMode: boolean;
  barRects: HistoryBarRect[];
  labelHitRects: HistoryLabelHitRect[];
  lockedAbsIndexes: Set<number>;
  selectedAbsIndex: number | null;
  selectedRelIndex: number | null;
  selectionClearTimer: number | null;
  visualSelectedAbsIndex: number | null;
  selectionZoom: number;
  selectionAnimRaf: number | null;
  slideDir: "left" | "right" | null;
};

export type DashboardCardSize = "full" | "half" | "quarter";

export type DashboardAvgRange = "past7" | "past30";
export type DashboardTimelineDensity = "low" | "medium" | "high";
export type DashboardMomentumDriverKey = "recentActivity" | "consistency" | "weeklyProgress" | "liveBonus";
export type DashboardRenderOptions = {
  includeAvgSession?: boolean;
  showBusy?: boolean;
  busyMessage?: string;
};

export type TaskTimerMutableState = {
  deletedTaskMeta: DeletedTaskMeta;
  tasks: Task[];
  editIndex: number | null;
  editDraftSnapshot: string;
  focusCheckpointSig: string;
  focusModeTaskName: string;
  focusShowCheckpoints: boolean;
  suppressAddTaskNameFocusOpen: boolean;
  confirmAction: null | (() => void);
  confirmActionAlt: null | (() => void);
  themeMode: "purple" | "cyan" | "lime";
  menuButtonStyle: "parallelogram" | "square";
  addTaskCustomNames: string[];
  weekStarting: DashboardWeekStart;
  startupModule: StartupModulePreference;
  taskView: "list" | "tile";
  dynamicColorsEnabled: boolean;
  autoFocusOnTaskLaunchEnabled: boolean;
  mobilePushAlertsEnabled: boolean;
  webPushAlertsEnabled: boolean;
  checkpointAlertSoundEnabled: boolean;
  checkpointAlertToastEnabled: boolean;
  optimalProductivityStartTime: string;
  optimalProductivityEndTime: string;
  rewardProgress: unknown;
  historyByTaskId: HistoryByTaskId;
  liveSessionsByTaskId: LiveSessionsByTaskId;
  historyRangeDaysByTaskId: Record<string, 7 | 14>;
  historyRangeModeByTaskId: Record<string, "entries" | "day">;
  focusModeTaskId: string | null;
  openHistoryTaskIds: Set<string>;
  pinnedHistoryTaskIds: Set<string>;
  hmExpandedTaskGroups: Set<string>;
  hmExpandedDateGroups: Set<string>;
  hmSortKey: "ts" | "ms";
  hmSortDir: "asc" | "desc";
  hmBulkEditMode: boolean;
  hmBulkSelectedRows: Set<string>;
  hmRowsByTask: Record<string, string[]>;
  hmRowsByTaskDate: Record<string, string[]>;
  historyViewByTaskId: Record<string, HistoryViewState>;
  addTaskMilestonesEnabled: boolean;
  addTaskMilestoneTimeUnit: "day" | "hour" | "minute";
  addTaskMilestones: Task["milestones"];
  addTaskCheckpointSoundEnabled: boolean;
  addTaskCheckpointSoundMode: "once" | "repeat";
  addTaskCheckpointToastEnabled: boolean;
  addTaskCheckpointToastMode: "auto5s" | "manual";
  addTaskPresetIntervalsEnabled: boolean;
  addTaskPresetIntervalValue: number;
  timeGoalModalTaskId: string | null;
  timeGoalModalFrozenElapsedMs: number;
  timeGoalReminderAtMsByTaskId: Record<string, number>;
  addTaskWizardStep: 1 | 2 | 3 | 4 | 5;
  addTaskType: "recurring" | "once-off";
  addTaskOnceOffDay: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
  addTaskPlannedStartTime: string;
  addTaskPlannedStartOpenEnded: boolean;
  addTaskDurationValue: number;
  addTaskDurationUnit: "minute" | "hour";
  addTaskDurationPeriod: "day" | "week";
  focusSessionNotesByTaskId: Record<string, string>;
  addTaskNoTimeGoal: boolean;
  elapsedPadTarget: HTMLInputElement | null;
  elapsedPadMilestoneRef: {
    task: Task;
    milestone: { hours: number; description: string };
    ms: Task["milestones"];
    onApplied?: () => void;
  } | null;
  elapsedPadDraft: string;
  elapsedPadOriginal: string;
  dashboardEditMode: boolean;
  dashboardDragEl: HTMLElement | null;
  taskDragEl: HTMLElement | null;
  dashboardOrderDraftBeforeEdit: string[] | null;
  dashboardCardSizes: Record<string, DashboardCardSize>;
  dashboardCardSizesDraftBeforeEdit: Record<string, DashboardCardSize> | null;
  dashboardCardVisibility: Record<string, boolean>;
  dashboardAvgRange: DashboardAvgRange;
  dashboardTimelineDensity: DashboardTimelineDensity;
  dashboardMenuFlipped: boolean;
  currentAppPage: AppPage;
  currentTileColumnCount: number;
  suppressNavStackPush: boolean;
  lastNativeBackHandledAtMs: number;
  checkpointToastQueue: Array<{
    id: string;
    title: string;
    text: string;
    checkpointTimeText?: string | null;
    checkpointDescText?: string | null;
    taskName?: string | null;
    counterText?: string | null;
    autoCloseMs: number | null;
    autoCloseAtMs?: number | null;
    taskId?: string | null;
    muteRepeatOnManualDismiss?: boolean;
  }>;
  activeCheckpointToast: {
    id: string;
    title: string;
    text: string;
    checkpointTimeText?: string | null;
    checkpointDescText?: string | null;
    taskName?: string | null;
    counterText?: string | null;
    autoCloseMs: number | null;
    autoCloseAtMs?: number | null;
    taskId?: string | null;
    muteRepeatOnManualDismiss?: boolean;
  } | null;
  checkpointBeepAudio: HTMLAudioElement | null;
  checkpointBeepQueueCount: number;
  checkpointRepeatStopAtMs: number;
  checkpointRepeatActiveTaskId: string | null;
  checkpointAutoResetDirty: boolean;
  historyNoteCloudRepairAttempted: boolean;
  checkpointFiredKeysByTaskId: Record<string, Set<string>>;
  checkpointBaselineSecByTaskId: Record<string, number>;
  cloudPreferencesCache: unknown;
  cloudDashboardCache: unknown;
  cloudTaskUiCache: unknown;
  navStackMemory: string[];
  pendingTaskJumpMemory: string | null;
  groupsIncomingRequests: FriendRequest[];
  groupsOutgoingRequests: FriendRequest[];
  groupsFriendships: Friendship[];
  groupsSharedSummaries: SharedTaskSummary[];
  ownSharedSummaries: SharedTaskSummary[];
  shareTaskIndex: number | null;
  shareTaskMode: "share" | "unshare";
  shareTaskTaskId: string | null;
  exportTaskIndex: number | null;
  groupsLoading: boolean;
  groupsLoadingDepth: number;
  groupsRefreshSeq: number;
  activeFriendProfileUid: string | null;
  activeFriendProfileName: string;
  historyEntryNoteAnchorTaskId: string;
  openFriendSharedTaskUids: Set<string>;
  workingIndicatorStack: Array<{ key: number; message: string }>;
  workingIndicatorKeySeq: number;
  workingIndicatorOverlayActive: boolean;
  workingIndicatorRestoreFocusEl: HTMLElement | null;
  dashboardBusyStack: Array<{ key: number; message: string }>;
  dashboardBusyKeySeq: number;
  dashboardBusyOverlayActive: boolean;
  dashboardBusyRestoreFocusEl: HTMLElement | null;
  dashboardBusyShownAtMs: number;
  dashboardBusyHideTimer: number | null;
  initialAuthHydrating: boolean;
  friendProfileCacheByUid: Record<string, FriendProfile>;
  cloudRefreshInFlight: Promise<void> | null;
  lastCloudRefreshAtMs: number;
  pendingDeferredCloudRefresh: boolean;
  lastUiInteractionAtMs: number;
  dashboardWidgetHasRenderedData: {
      tasksCompleted: boolean;
      momentum: boolean;
      focusTrend: boolean;
      heatCalendar: boolean;
      modeDistribution: boolean;
      avgSession: boolean;
      timeline: boolean;
    };
};
