import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const preHydrationThemeScript = `
    (function() {
      try {
        var keyBase = "taskticker_tasks_v1";
        var theme = String(localStorage.getItem(keyBase + ":theme") || "").trim().toLowerCase();
        var style = String(localStorage.getItem(keyBase + ":menuButtonStyle") || "").trim().toLowerCase();
        var body = document.body;
        if (!body) return;
        if (theme === "dark" || theme === "command" || theme === "light") {
          body.setAttribute("data-theme", theme);
        }
        if (style === "square" || style === "parallelogram") {
          body.setAttribute("data-control-style", style);
        }
      } catch (_) {}
    })();
  `;

  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: preHydrationThemeScript }} />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
